### ISSUE TITLE
Duplicated sealed products

### ISSUE THREAD

**Issue by kodawah** [mtgjson/mtgjson#1102]
there seems to be duplicated information for MB1

`CMB1` has "Mystery Booster Booster Box Convention Edition 2021" with a proper tcg identifier
`MB1` has "Mystery Booster Booster Box (Convention Edition - 2021)" with no identifier

same goes for packs -- I believe other editions are affected too

I think logically they belong to MB1 but they got put in CMB1 because of the playtest cards maybe?
Should we devise some form of deduplication mechanism?

**Comment by kodawah** [comment]
Warhammer 40,000 Collector's Edition Commander Decks - Set of Four: []
  Warhammer 40,000 Commander Decks - Set of Four: []
  Warhammer 40000 Commander Deck Display: []
  Warhammer 40000 Commander Deck Display Collectors Edition: []

i think they are the same 2 couples too

**Comment by kodawah** [comment]
Aether Revolt Prerelease Pack: []
  'Aether Revolt Prerelease Pack ': []

**Comment by kodawah** [comment]
Aether Revolt Planeswalker Deck Display: []
  Aether Revolt Planeswalker Decks - Set of 2: []

**Comment by kodawah** [comment]
The Lord of the Rings Tales of Middle earth Gift Bundle:
  'The Lord of the Rings Tales of Middle earth Bundle: Gift Edition': []

**Comment by ZeldaZach** [comment]
cc: @axxroytovu

**Comment by axxroytovu** [comment]
The ones that are duplicate within the same set are easy enough. We just add the names to mtgjson5/resources/sealed_name_fixes.json

The ones that are duplicated between different sets I have no idea how to resolve, since each set is built individually.

**Comment by axxroytovu** [comment]
> Aether Revolt Planeswalker Deck Display: [] 
> Aether Revolt Planeswalker Decks - Set of 2: []

These are actually different products. Set of 2 is one of each, the deck display is three of each.

**Comment by axxroytovu** [comment]
Considering how complex this mapping is, I'm seriously considering modifying the repo structure to filter all sealed product through https://github.com/mtgjson/mtg-sealed-content before it gets loaded here. Instead of just hosting a few "nonstandard" products, it would be the truth source for all sealed products and provide links to the CK and TCGP sites. I can have the daily script check upstream for new products easily enough, but it would be handled in the offboard repo before getting loaded here.

Pros: 
- This allows us to easily map between TCGPlayer and CardKingdom product locations, even when they aren't in the same set object
- This allows us to maintain product consistency even through data purges, like https://github.com/mtgjson/mtg-sealed-content/issues/76
- We no longer need complex name mapping tools if products are hard-linked with upstream ID numbers

Cons:
- This would overhaul the current sealed product flow
- This does rely on regular manual cleanup, though our current system also requires regular updates to the name mapper and content repos

Opinions and concerns?

**Comment by kodawah** [comment]
as long as product ids don't change, i think this is a good solution

**Comment by axxroytovu** [comment]
The product uuid is based entirely off the product name. So as long as those stay the same the product ids should stay consistent. 

I will be making fixes to some names, like how `40000` and `40,000` are used inconsistently for the 40k sets, but I will do my best to keep the product names as constant as possible.

**Comment by kodawah** [comment]
oh, also since sealedProduct is in a supported release and there is code utilizing it, maybe we should consider a transition period where we have two fields containing the same data (maybe just `product`) in order to avoid breakage

**Comment by kodawah** [comment]
also as mentioned in discord we could add the "base language" field for any particular product

**Comment by axxroytovu** [comment]
40K - resolved
MB1 vs CMB1 - All products should be part of MB1, correct? Validating before I make changes.
AER - resolved or by design
LTR - resolved

See https://github.com/mtgjson/mtg-sealed-content/pull/84

All further duplicate product issues should be brought up in the sealed-content repo.

**Comment by kodawah** [comment]
> MB1 vs CMB1 - All products should be part of MB1, correct? Validating before I make changes.

i think so, even if retail foils are in a diff edition, i think they all belong in the same mb1 umbrella

> All further duplicate product issues should be brought up in the sealed-content repo.

ok

**Comment by axxroytovu** [comment]
Mystery booster duplicates fixed with https://github.com/mtgjson/mtg-sealed-content/pull/86

**Comment by kodawah** [comment]
i *think* this can be closed since we moved to the custom list
