### ISSUE TITLE
wastes rarity

### ISSUE THREAD

**Issue by aeosynth** [mtgjson/mtgjson#111]
http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=407693

> Rarity: Common

mtgjson has rarity as 'basic land'

**Comment by lsmoura** [comment]
So... Which one is the correct one? Wizards itself said that they are "2x Common", but it is still a basic land (there is no limit on constructed decks)... But, even tough it is a basic land, you can't bring them to limited.

Oh, this is so confusing...

I'll change the json file to:

> Rarity: "Go figure!"

Seriously, tough. What's the best option?

**Comment by Garbee** [comment]
Either someone messed up the gatherer info or they are making it "common" since it doesn't have a type.

Or, on another end they are making them Common for *this set* since they are going to be printed at an extra common rate. Which isn't tied to the Basic Land print rate.

It will be interesting to see if the next set wastes is in has Common or Basic Land rarity.

Personally, as far as the API is concerned and programmers building things to compute based on the data, just keep `Basic Land`. That is exactly what it is and will make filtering/searching based on the data much easier (rather than devs needing to program around this bad logic on Wizard's part.)

If someone wants/needs **"absolute data purity"** then they can program in this little glitch within their own data structures.

**Comment by aeosynth** [comment]
wastes are twice as common because the versions with different art count as separate cards

the type is still `basic land` in both gatherer and mtgjson, so i don't see the issue wrt searching

**Comment by Garbee** [comment]
Do  people want lands showing in a common card filter?

**Comment by aeosynth** [comment]
yes? http://gatherer.wizards.com/Pages/Search/Default.aspx?action=advanced&type=+[%22Land%22]&rarity=+[C]

**Comment by galaxyoyo** [comment]
I think the rarity of Wastes have to be basic land. Wizards have well emphasized that Colorless will take place in the pentagone, and Wastes will be a basic land entirely.

**Comment by Garbee** [comment]
Ok, rephrase that question to "basic lands showing up in common queries". There of course are plenty of lands that are common, but they have alternate abilities than basic mana that is a pure one-to-one generation.

There is no reason to modify this on the APIs point. It is clear, these are *basic lands*. Wizards is psyco and categorizing them as commons simply based on their print-run numbers. Not based on what the cards are compared to the other basic lands.

**Comment by Fryyyyy** [comment]
Wastes says "C" on the card, and doesn't appear in the basic land slot of the booster.  I think it's straight up incorrect to say its rarity is "basic land".

**Comment by aeosynth** [comment]
this is mainly an issue for booster generators, where wastes do not behave like 'regular' basic lands

**Comment by Fryyyyy** [comment]
Agreed, which is precisely what I use it for :)

**Comment by aeosynth** [comment]
it is clear that wastes are basic lands, which is why their type is `basic land`. their rarity is separate from their type.

**Comment by fenhl** [comment]
This is still an issue and needs to be fixed. The rarity of a card is separate from its type line. Gatherer, the booster distribution, and the collector info in the lower-left corner of the card all say that Wastes is at common, not land rarity.
