### ISSUE TITLE
SLD/SLX Cards in AllDeckFiles.json

### ISSUE THREAD

**Issue by the-muppet** [mtgjson/mtgjson#1119]
#### Version(s) tested against
MTGJSON v5.2.2+20230916

#### Description of Bug
The Walking Dead Secret Lair Drop is being populated with the new SLX versions of the cards rather than what actually come in the lair.
I.E Greymond, Avacyn's Stalwart in lieu of Rick, Steadfast Leader. Even if "errata'd" to be the same card - there should be a distinction made for these sealed product lists.

**Comment by axxroytovu** [comment]
This is an upstream issue. I created an issue in the deck host repo and linked it.

**Comment by axxroytovu** [comment]
After digging in further, I don't think this is an issue. The cards in the deck list are correct. When they released the SLX cards, the official "magic" name of the original cards was updated, but the UUID and "flavor name" of the cards are unchanged.

**Comment by the-muppet** [comment]
Good day!
So that would mean that there is now a subset of cards for which the
"official names" are not within the 'Name' kv pair in that json object, and
instead its found within the 'FlavorName'.. even though the physical cards
that come in that Lair, are what is being shown as 'FlavorName', but when
parsed according to documentation - return different cards, with different
SKUs, market values, etc. associated with them.
This is by design?

**Comment by axxroytovu** [comment]
So the official magic name of SLD:143 is "Greymond, Avacyn's Stalwart". Even though "Rick" is printed on the card. If you had a Pithing Needle, you would name Greymond in order to have the intended effect. And if you look at Scryfall's entry for the card, Greymond is the name at the top of the page. https://scryfall.com/card/sld/143/greymond-avacyns-stalwart

All of the card mapping is done by collector number, and SLD:143 is the same card it always was. I'm not sure what you mean by "parse according to the documentation," but im happy to look through it.

**Comment by ZeldaZach** [comment]
Did some further looking into this, and I feel things are correct as-is. When cards get an in universe printing, the name of the "original" card gets updated, with a flavorName update. This doesn't change the entity across MTGJSON, but it becomes more accurate with newer information. Similar to an Oracle update.
