### ISSUE TITLE
Bug: 'signed' appears in finish data

### ISSUE THREAD

**Issue by therealpurplemana** [mtgjson/mtgjson#1187]
I'm observing 'signed' appear alongside 'nonfoil' for cards with only a single printed variation. 

Steps to reproduce:
- Example mtgjson   "uuid": "389aca11-e5c2-5838-b6c6-d3a6ef116f4b",
- Corresponding scryfall: 9987d80f-d2cb-4cc1-b728-1506d2d41cde (https://api.scryfall.com/cards/9987d80f-d2cb-4cc1-b728-1506d2d41cde?format=json&pretty=true)

Expectation:  Each 'finish' should represent a single printed variant of that card.

I'm only part way through the data but I see over 1280 instances so far

cc @koda @ZeldaZach

**Comment by therealpurplemana** [comment]
Was there any resolution on this one ?

**Comment by kodawah** [comment]
i don't see "signed" anywhere, probably it got fixed upstream

**Comment by ZeldaZach** [comment]
Signed is apart of cards that are, well, signed. It was put into the finishes array because it's considered a finish on the card, in my opinion. This is documented over at https://mtgjson.com/data-models/card/card-set/#finishes. Note that your expectation is not apart of the documentation. However, I can see where your confusion might come from, and a documentation update to indicate "signed" isn't necessarily a finish on its own, or that finishes might overlap, could be due.

Will cut a ticket on the other repo.

cc @staghouse
