### ISSUE TITLE
The flipped face of flip cards is missing the mana cost

### ISSUE THREAD

**Issue by KingSupernova31** [mtgjson/mtgjson#139]
Dokai, Weaver of Life should have manaCost: "{1}{G}", but it does not have any manaCost listed.

**Comment by ZeldaZach** [comment]
I don't know if I agree with this, as it doesn't have a printed mana cost... Can you provide some reasons why this should be added?

**Comment by KingSupernova31** [comment]
Because that's its mana cost. Didn't we already go over this in the Discord?

**Comment by ancestral** [comment]
I’m thinking this is correct as-is. The reason is, on a flip card (instead of a split card), you can only cast one part — in this case, Budoka Gardener.

Let’s take a step back. There are a few ways to list and manage cards:

* Each part of a card (split and flip cards)
* Each face of a card (double-face cards and meld cards)
* Each physical card

Budoka Gardener // Dokai Weaver is one physical card, with one face and two parts.

Gatherer has each part of [Budoka Gardener // Dokai Weaver individually](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=451089), though listed together on the same page. They share a multiverse ID of 451089. Gatherer has some issues displaying some of this stuff; when you click “Printed”, you’ll see Dokai’s info isn’t listed. (Nice job, Wizards!) With all that in mind, both parts contain a mana cost of {1}{G} (even though it’s only featured on Budoka). Is this a mistake? (I think it is, as Budoka Gardener is the only part that can be cast.)

Scryfall lists this card on one page, with each part running together. It lists the CMC of the card as a whole at 2.0. The Budoka Gardener has a CMC of 2.0, whereas Dokai has no CMC listed. So is this a mistake? (The way Scryfall does it, they report the CMC of the total card — the sum of the mana cost for both parts. If you list {1}{G} on both, then that adds up to 4.0, which certainly isn’t correct.)

(We did discuss similar stuff for a while in issue #42.)

**Comment by KingSupernova31** [comment]
@ancestral It is not a mistake. Dokai has a mana cost of {1}{G}. It's really as simple as that. That's its oracle text. If you want to say that its printed text has no mana cost, I won't argue with you there. But MTGJSON goes by oracle text, not printed text, and its oracle text has a mana cost of {1}{G}. It's just a fact, there's no opinion about it.

**Comment by ancestral** [comment]
I discussed this with Magic judges. 709.1c says when flipped, nothing changes, so yes, the card still has a mana cost of {1}{G}. However, the parts (I should have used the word “halves” or “faces”) don’t contain any mana costs, only the card does. Per the comprehensive rules:

> **709.1a** The top half of a flip card contains the card’s normal name, text box, type line, power, and toughness. The text box usually contains an ability that causes the permanent to “flip” if certain conditions are met.

> **709.1b** The bottom half of a flip card contains an alternative name, text box, type line, power, and toughness. These characteristics are used only if the permanent is on the battlefield and only if the permanent is flipped.

Having the mana cost on each face would be incorrect. Which means maybe we should submit a bug report upstream to Scryfall seeing they have one on the Budoka Gardener face.

**Comment by KingSupernova31** [comment]
If it helps, I am also a judge. But that's not really relevant here. What's relevant is the fact that Gatherer is the official source of oracle text. Gatherer says that it has mana cost {1}{G}, so that's what MTGJSON should reflect. You're trying to claim that WOTC's rules have a bug.

Additionally, you're being inconsistent. If you want MTGJSON to reflect printed text, then you're going to need to change a bunch of other fields too, like CMC and color on double-faced cards and meld cards. Double-faced cards have no printed mana cost, and yet MTGJSON does the (correct) thing and gives them a CMC in the JSON, because that's what the rules and the oracle text say.

**Comment by ZeldaZach** [comment]
Lets try to keep things free flowing and relaxing, if possible

There seems to be arguments for both sides of the equation. At this current moment, MTGJSONv4 relies more on Scryfall than Gatherer for its information. The amount of users who are impacted by us neglecting a component of Gatherer in favor of a more steady data stream should be a minority.

If this were to change over to being a majority impact, I would gladly reconsider this issue. Like I've said in the past, we are not trying to be the rules engine. Our goal is to provide data and allow developers to implement what they see fit.

Ex: We split up the CMC on split cards because it didn't make sense to list them combined, even though the rules say they should be.

Since the rotated/flipped side does not have a printed mana cost, I am hesitant to include it. Adding the CMC was done in version 3, so to keep some backwards capacity I reimplemented it here. 

I hope you all understand and accept the choices I make while leading this project. My goal is to try and appease as many people as possible, but there are times when we come across things that are not worth the time and we can leave it up to developers to decipher as they see fit.

**Comment by KingSupernova31** [comment]
"The amount of users who are impacted by us neglecting a component of Gatherer in favor of a more steady data stream should be a minority."

You are providing incorrect data. Just because you aren't seeing other people chime in and complain about it doesn't mean that they don't exist. A lot of MTG developers don't use MTGJSON and make their own data source instead, and I'm sure things like this are one of the reasons why.


"Like I've said in the past, we are not trying to be the rules engine."

Except you are. Cards don't have a color printed on them. The rules of the game tell you to derive the color from the mana cost, color indicator, and color-changing abilities as appropriate. And yet you include color in the JSON.


"Since the rotated/flipped side does not have a printed mana cost.."

It does have a printed mana cost. When a card flips, its name, type, rules text, etc change to the flipped characteristics. The mana cost isn't one of the characteristics that changes. It keeps its printed mana cost.


@ZeldaZach I'm a little confused by your responses here- I thought you agreed with me when we spoke in the Discord. What changed?

**Comment by ZeldaZach** [comment]
@KingSupernova31 for those who choose not to use MTGJSON, that is their own prerogative. I am trying to do what I feel is best for the project with my decisions.

At the current time, I don't feel adding the printed mana cost from the front face is appropriate. I spoke with SF and a few friends outside the project and they all came to a similar idea that it doesn't make a lot of sense to print what's not there.

We'll be certain to document such instances, but I am content with how rotate cards are being handled currently.
