### ISSUE TITLE
Invalid UUIDs

### ISSUE THREAD

**Issue by NickBranstein** [mtgjson/mtgjson#169]
#### Description of Bug:
Fire and Ice from UMA both have invalid UUIDs in this version. It appears an extra character was inserted into them making them an invalid UUID format (the last grouping should be 12 digits and these have 13 now).

- In 4.1.2 Ice (UMA) is '3f822331-315e-4297-bb69-f1069032c6c51' in a previous version the UUID was '3F822331-315E-4297-BB69-F1069032C6C1'
- In 4.1.2 Fire (UMA) is '3f822331-315e-4297-bb69-f1069032c6c50' in a previous version the UUID was '3F822331-315E-4297-BB69-F1069032C6C0'

In both cases I believe the 5 at the end of the IDs was somehow inserted by mistake and shouldn't be there as I assume these ids are not meant to change between version (or be invalid in their format).

**Comment by ZeldaZach** [comment]
So this was intentional. What I did in the prior rendition was cut off the last character (which was a 5) and the append the index (0 or 1). I am trying to figure out an appropriate way to give two different UUIDs to the halves, while still keeping them close so you can card find with them.

If you have a better solution, please feel free to propose it.

**Comment by NickBranstein** [comment]
I think that approach is fine but it looks like in 4.1.2 the 5 somehow snuck back into the mix so you can't parse the string as a valid UUID format because there are 13 digits in the last part of the string.

**Comment by ZeldaZach** [comment]
If you check out the [4.1.3 changelog](https://mtgjson.com/v4/changelog.html) we describe the change we've made. 
> UUIDs for split cards, meld cards, and split tokens are 37 characters in length (with the first 36 characters being the same between them)

I'm trying to think of the best way to handle split cards / cards with multiple faces, as I give each a unique ID. If my current strategy is poor, another idea I have is that I can modify the last value and run a modulo incrementer (i.e. Fire/Ice = "12345" => Fire = "12345" Ice = "12346")

**Comment by NickBranstein** [comment]
Thanks for that explanation I did not see it earlier. I think if you're going to call that field a UUID it should conform to the standard 36 character length or change the name of the field. If you decide to leave it as a "UUID" then think incrementing the last digit would work fine and also maintain the valid UUID formatting.

**Comment by excention** [comment]
Between this purposed path and adding the index on the end the index is better, but only if scryfall accepts the exact UUID and brings back the full card image....
Otherwise it will get confusing from one card to the next what UUID you need to use if you are doing +1 to the side a for each side. In cases like Who/what/where/when/why. 

Conforming to the UUID standard not sure that it matters as long as the potential max character length is documented ... the idea is the same, It's a unique ID and no one outside your DB is going to be creating them... So if all anyone is going to do is consuming it then why does it matter?

Scott



> If you check out the [4.1.3 changelog](https://mtgjson.com/v4/changelog.html) we describe the change we've made.
> 
> > UUIDs for split cards, meld cards, and split tokens are 37 characters in length (with the first 36 characters being the same between them)
> 
> I'm trying to think of the best way to handle split cards / cards with multiple faces, as I give each a unique ID. If my current strategy is poor, another idea I have is that I can modify the last value and run a modulo incrementer (i.e. Fire/Ice = "12345" => Fire = "12345" Ice = "12346")

**Comment by NickBranstein** [comment]
> Conforming to the UUID standard not sure that it matters as long as the potential max character length is documented ... the idea is the same, It's a unique ID and no one outside your DB is going to be creating them... So if all anyone is going to do is consuming it then why does it matter?

In languages (not js) where UUID/Guid is natively supported, then users consuming would/could/should be using these types to parse a UUID and do validation.

Either way it doesn't ultimately matter to me this is more of a semantics argument at this point because I don't fully understand the purpose of this field if split cards are getting different unique ids when they aren't really cards themselves but half cards.

**Comment by ZeldaZach** [comment]
So i'll be changing how this is done (again)

id = my own UUID 
scryfallId = UUID given by scryfall

That way I can repeat the values for scryfall, but have my own that people can key with
