### ISSUE TITLE
New card layout in Eldritch Moon - Meld

### ISSUE THREAD

**Issue by tritoch** [mtgjson/mtgjson#187]
Eldritch Moon introduces a new card layout - Meld.  These cards are DFC - except the back side only contains half of a card - either 'top' or 'bottom' and the fronts are spread across two cards.

Issues #135 and #146 both reference methods users have for determining the 'front' of current DFC and should attempt to be supported.

**Comment by fenhl** [comment]
Summarizing some of the discussion from gitter:

*   The back faces should be treated as a single card.
*   The names field in each of the 3 entries should list all 3 card names in a well-defined and documented order.
*   Additionally, the layout field should be set to meld-top, meld-bottom, and meld-back.
*   How should card numbers work?

**Comment by Daenyth** [comment]
> How should card numbers work?

IMO Use the card number of the "top" piece

**Comment by tritoch** [comment]
> > How should card numbers work?

> IMO Use the card number of the "top" piece

The 'bottom' piece has the card number from its front side written on it.

Given cards A and B, if card A is card number 001, and has the text "meld them into...", it will be on top.  Card 002 will have "(melds with..." and be on bottom.  The (flipped) melded cards will have the card number 002 on the bottom and have the highest rarity of the two meld components on it as well. So you can assign the conglomerate the top card number, but when they're both flipped, you'll only see the bottom card's card number.

**Comment by fenhl** [comment]
Do we have any confirmation that it's highest rarity, and not just that of the top half?

**Comment by tritoch** [comment]
> Do we have any confirmation that it's highest rarity, and not just that of the top half?

No, but all are spoiled, and only one of them has different rarities, and it's the rarity of the 'top' card where the symbol is on the 'bottom' card.

**Comment by fenhl** [comment]
Right now, the names field is inconsistent. Brisela and Chittering Host list the card with the meld ability as the second name, while Hanweir lists it as the first. Could this be changed to my suggestion from above, so that all 9 cards would have the following names fields?

*   `["Gisela, the Broken Blade", "Bruna, the Fading Light", "Brisela, Voice of Nightmares"]`
*   `["Graf Rats", "Midnight Scavengers", "Chittering Host"]`
*   `["Hanweir Battlements", "Hanweir Garrison", "Hanweir, the Writhing Township"]`
