### ISSUE TITLE
Rarity incorrect documentation for timeshifted cards

### ISSUE THREAD

**Issue by synercoder** [mtgjson/mtgjson#201]
#### Description of Bug:
I used the documentation to create my own C# client. I created an enum type for rarity since the documentation stated that it could only be one of five values. Now I try to parse all the sets and I got a parse error:

Error converting value "timeshifted uncommon" to type 'MtgJson.Models.Rarity'. Path 'cards[17].rarity', line 2215, position 44.

I see from issue #125 that this was added, but for what reason? 

If a card has rarity rare, and is timeshifted... why should the rarity be "timeshifted rare"? It is still a rare. 

I think that either remove timeshifted from the rarity field, or change the documentation to reflect the duplicate timeshifted rarities.

**Comment by JayDi85** [comment]
Remarks for @ZeldaZach -- there are two rarity types. One from gatherer -- it's a "booster" rarity and can contains "special" (e.g. it's a booster slot type). And one from scryfall -- it's a real rarity (e.g. it's a card's rarity icon). [Info from scryfall admins](https://github.com/scryfall/gatherer-bugs/issues/34).

**Comment by ZeldaZach** [comment]
My rarity fields are based on Scryfall, with the exception that cards from TSP can have the `"timeshifted" + $rarity` combination. If y'all feel this is wrong (and I should leave it up to the implementer to understand `if isTimeshifted then rarity = "timeshifted" + rarity` then I'm fine changing it back. Otherwise, we can update documentation to fit what's listed.

**Comment by synercoder** [comment]
I dont personaly see the benefit of having "extra/double" timeshifted rarities. 

Like you said @ZeldaZach in my own code I can use: `if isTimeshifted then rarity = "timeshifted" + rarity`

Instead I now have code that strips the timeshifted from the rarity.

But then again... I am not the only user of mtgjson ^^.

**Comment by ZeldaZach** [comment]
I added it to match the requests of the booster field, but not enough people chime in on what they'd like to see, so I constantly have to be making changes.

I'm fine stripping it again, and leaving that to the end user, but i could also just document it

**Comment by synercoder** [comment]
Either way is eventually fine for me.

**Comment by magreenblatt** [comment]
Personally, I would prefer not to have "timeshifted" or other prefixes on the "rarity" values in card records because (a) it makes parsing more complicated, and (b) it's redundant with existing flags like isTimeshifted.

Prefixes included with the "boosterV3" values ("timeshifted", "double faced", "foil") are fine for now. We can discuss possible improvements to the booster representation at some point in the future.
