### ISSUE TITLE
Latest update broke 30 of 40 flip cards

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#240]
They're gone, replaced with half of themselves.

Only ones not broken seem to be ones from Betrayers of Kamigawa.

**Comment by lsmoura** [comment]
=(

**Comment by Psithief** [comment]
I think there needs to be a [gatherer error] label to go with these.

**Comment by csuhta** [comment]
Gatherer has completely fucked up the flip card pages. What is happening.

http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=247175

![cyms5kes](https://cloud.githubusercontent.com/assets/769083/19368191/e3355a38-916c-11e6-9c4b-2a5fe5a7672e.png)

**Comment by taw** [comment]
If it's just a localized gatherer fuckup, just revert the few affected sets to previous version.

**Comment by csuhta** [comment]
I'm working around this issue, and here's what I've discovered:

Gatherer has done an incomplete/strange migration for the flip cards. They all seem to be moving to the `&part`-style Gatherer URLs.

Passing the `part` parameter correctly gets the desired card face here:

- http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=247175&part=Nezumi+Graverobber
- http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=247175&part=Nighteyes+the+Desecrator

This is the same way it works for things like Fire/Ice:

- http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=292753&part=Ice
- http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=292753&part=Fire

Most of the flip cards work correctly, but **as this post the following flip cards are damaged, and their pages don't work correctly**:

Callow Jushi
Jaraku the Interloper
Hired Muscle
Scarmaker

Note how this doesn't work for both URLs, and the first URL shows `----` in the card text instead of correctly splitting it into two halves:

- http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=74489&part=Callow+Jushi
- http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=74489&part=Jaraku+the+Interloper

The site doesn't even think there is a card named Juraku the Interloper right now:

- http://gatherer.wizards.com/Pages/Search/Default.aspx?name=+[Jaraku]+[the]+[Interloper]

**Comment by bakert** [comment]
Is this waiting on Gatherer to be fixed before it can be fixed? If not, can I help? I'm down to do whatever is needed to clear this up if someone wants to give me the 2 minute high level overview.

**Comment by lsmoura** [comment]
@bakert -- We're rebuilding everything at https://github.com/mtgjson/mtgjson4 It should be all done in a couple of days.

**Comment by bakert** [comment]
Sweet, thanks!

**Comment by bakert** [comment]
Did this get done. Is there a beta site to pull the more up to date info from? Thanks!

**Comment by tritoch** [comment]
The flip sets are available at https://github.com/mtgjson/db/tree/flip for now

**Comment by dgant** [comment]
Cards in the flip sets at https://github.com/mtgjson/db/tree/flip are missing the "id" property. They have an "_id" property but that's a different value (and, I imagine, not intended to be consumed).

Day of Destiny in BOK (AllSets-x.json): "id":"38db6428d7da372e52625a8172e6f5cf192fc93f"
Day of Destiny in BOK (BOK.json): "_id":"d3299276-dd17-4113-33e3-d3a3b8818160"

I've tried to work around it by recreating the ids myself, but that's a surprisingly deep rabbit hole.

Is mtgjson4 close, or is there a way to produce the flip sets with the id property?

**Comment by lsmoura** [comment]
@dgant Better fix the flip.

**Comment by CaseyWalsh** [comment]
I just noticed (v3.7.1) that the flip card 'Erayo, Soratami Ascendant // Erayo's Essence' contains only the 'Erayo's Essence' part, and bills it as "layout":"normal" & "manaCost":"{1}{U}".  Is this part of the 'Kamigawa Flip Cards' bug?

**Comment by csuhta** [comment]
I wanted to let you all know that the Scryfall team reported this page issue to Wizards, and they told us that would look into.

**Comment by dgant** [comment]
Just chiming in to say it would be a huge help for this to be resolved on the MTGJson side. Waiting on Wizards to fix Gatherer bugs could be an exercise in extreme patience.

**Comment by MidnightLightning** [comment]
I just ran into this bug today, and it looks like Gatherer at this moment doesn't have separate pages for the "part" specifications on flip cards (as was reported on Oct. 16, 2016 in this comment thread), but now both parts are shown on one page:

Nezumi Graverobber // Nighteyes the Desecrator: http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=247175

One multiverse ID for the two of them, though different "Card Number" listed (92a and 92b)

**Comment by taw** [comment]
By the way - for sake of http://mtg.wtf/  I maintain [a "fixed" version of mtgjson](https://raw.githubusercontent.com/taw/magic-search-engine/master/data/AllSets-x.json).

I have a script that takes new mtgjson db and selectively replaces broken parts with old mtgjson data.

Most people are probably better off using my version instead of mtgjson's.
