### ISSUE TITLE
GRN guild gates have no foreignData

### ISSUE THREAD

**Issue by robertjanetzko** [mtgjson/mtgjson#246]
#### Description of Bug:
The guildgates for GRN don't have any foreignData. 
It seems as even gatherer doesn't connect the english version with the others:

english: http://gatherer.wizards.com/Pages/Card/Languages.aspx?multiverseid=452995 (no other languages)
german: http://gatherer.wizards.com/Pages/Card/Languages.aspx?multiverseid=453254 (all other languages except english)

**Comment by ZeldaZach** [comment]
~~The issue is gatherer doesn't have the data, as you have figured out, so Scryfall has no basis for marking the cards since they don't have the translations. As such, we can't really add the data either, as we have no reliable source of data. Unfortunately this is a no-fix upstream issue for the time being :(~~

Interesting find, I didn't read your ticket closely! I'll report this upstream :)
