### ISSUE TITLE
Mythic Edition Set Contains cards from two sets

### ISSUE THREAD

**Issue by vrspectre** [mtgjson/mtgjson#257]
#### Description of Bug: When viewing the all cards there is a set named Mythic Edition. Code is MED. 

Cards like Kaya, Orzhov Usurper (456589) and Elspeth, Knight-Errant (456589) both show in that set. However they are listed in different sets according to gatherer.  Ravnica Allegiance Mythic Edition and Guilds of Ravnica Mythic Edition respectively.

**Comment by ZeldaZach** [comment]
Scryfall classifies them as independent sets, which is why it appears that way. I'm more inclined to go with the Scryfall split up, as Gatherer is too unpredictable with what they do to get this correct. This is a data selection option, and you're free to combine the data how you choose.

Lmk if you have any other questions!

**Comment by vrspectre** [comment]
I think there's some confusion. 

Scryfall has them both in the same set. It's Gatherer and TCG and other things that list them out as separate sets. 
https://scryfall.com/card/med/GR1/elspeth-knight-errant
https://scryfall.com/card/med/RA8/kaya-orzhov-usurper

My best guess is that it was listed as MED when GRN came out and then when RNA came out gatherer probably split MED into two sets. And that's how the mythic got combined. 

so the issue appears to be the the source data from Scryfall. but I can't seem to find a way to report in on their side.
