### ISSUE TITLE
[All is Dust] missing in AllCards-x

### ISSUE THREAD

**Issue by vanyamil** [mtgjson/mtgjson#272]
Title

**Comment by lsmoura** [comment]
`"All Is Dust":{"layout":"normal","name":"All Is Dust","manaCost":"{7}","cmc":7,"type":"Tribal Sorcery — Eldrazi","types":["Tribal","Sorcery"],"subtypes":["Eldrazi"],"text":"Each player sacrifices all colored permanents he or she controls.","imageName":"all is dust","rulings":[{"date":"2010-06-15","text":"A colored permanent is a permanent with at least one colored mana symbol in its mana cost. Note that effects may cause a colored permanent to become colorless (as Moonlace could), or a colorless permanent to become colored (as Crimson Wisps could)."},{"date":"2010-06-15","text":"Tokens may also be colored permanents. The effect that creates a token states what color it is or whether it's colorless."},{"date":"2010-06-15","text":"Lands have no mana cost, so they are colorless unless an effect states otherwise."},{"date":"2010-06-15","text":"All the colored permanents are sacrificed at the same time."},{"date":"2013-07-01","text":"All Is Dust doesn't destroy permanents. Rather, it causes them to be sacrificed. Regeneration, totem armor, and indestructibile can't save permanents from All Is Dust."}],"printings":["pGPX","ROE","MM2"],"legalities":[{"format":"Commander","legality":"Legal"},{"format":"Legacy","legality":"Legal"},{"format":"Modern","legality":"Legal"},{"format":"Vintage","legality":"Legal"},{"format":"Zendikar Block","legality":"Legal"}]}`

It's there.

**Comment by lsmoura** [comment]
@vanyamil Where are you not finding it?
Here's the official URL: http://mtgjson.com/json/AllCards-x.json
Here's the alternate URL: http://mtgjson.net/json/AllCards-x.json
Here's the 3.8 specific URL: http://mtgjson.net/json-3.8/AllCards-x.json

I can find it on all of those files (which are essentially the same).

I'm closing this. If it's still an issue, please, reopen.

**Comment by vanyamil** [comment]
Oh, it takes a capital letter...Sorry!
