### ISSUE TITLE
Support for Scryfall

### ISSUE THREAD

**Issue by ZeldaZach** [mtgjson/mtgjson#31]
The awesome people at Scryfall have given us an unlimited API key to gather data from them for validation purposes and specialty sets that Gatherer doesn't contain.

I'd like our focus to be on 100% gatherer parsing for the moment, but this is a great next step once that's done. This will be a replacement for MCI as they have been unresponsive to requests.

**Comment by ZeldaZach** [comment]
Critical note ->  Linking: https://github.com/mtgjson/mtgjson-python/issues/26#issuecomment-403334670

**Comment by csuhta** [comment]
(I'm a member of the Scryfall team) 

Regarding the linked comment https://github.com/mtgjson/mtgjson-python/issues/26#issuecomment-403334670:

> Their API is a paid service, so providing a full download of their work seems like we're hurting their business model

This is not quite correct. Our API and images are free for everyone to use, but we have (fairly reasonable) rate limits. If you exceed them, our API may return a 429 status code to you so that you slow down. 

We encourage businesses that depend on our data to voluntarily [support us at the $15 level](http://scryfall.com/pricing), and we provide priority support if you do.

Separately, we have a beta program where registered applications can make API requests with a secret key, and those applications receive much more lenient rate limits. That is what we have provided to the MTGJSON team.

Please feel free to use our API in whatever capacity here to check or sync any additional data. ❤️

**Comment by ZeldaZach** [comment]
Moved towards a hybrid between Gatherer/SF

**Comment by tooomm** [comment]
Is there any documentation on how this works?
Like which data comes from Gatherer and which from Scryfall?
