### ISSUE TITLE
Incorrect printing data for "Forsaken Wastes"

### ISSUE THREAD

**Issue by zhelu** [mtgjson/mtgjson#331]
In AllCards-x.json:

  "Forsaken Sanctuary": {
    "layout": "normal",
    "name": "Forsaken Sanctuary",
    "type": "Land",
    "types": [
      "Land"
    ],
    "text": "Forsaken Sanctuary enters the battlefield tapped.\n{T}: Add {W} or {B} to your mana pool.",
    "imageName": "forsaken sanctuary",
    "printings": [
      "SOI",
      "AKH"
    ],
    "legalities": [
      {
        "format": "Amonkhet Block",
        "legality": "Legal"
      },

This card is NOT in the AKH set (and by extension not legal in Amonkhet block).

**Comment by zhelu** [comment]
Also, just to preemptively fend of this concern, the dual lands that are in the Planeswalker decks are Stone Quarry and Foul Orchard.

**Comment by Garbee** [comment]
The problem is, they are listed [in Gatherer](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=429673) as being in the set. So there is something wrong on Wizards end or there is something we haven't seen yet (as they literally have full card art with the set symbol for AKH for these cards.)

Is there any official word from Wizards of the Coast on whether or not these are mistaken listings?

**Comment by emerald000** [comment]
The 10 tap lands from SOI/OGW are found in the Deckbuilder's Toolkit with the Amonkhet symbol and are legal in Standard.

**Comment by Garbee** [comment]
Sweet. So this issue can be closed up then since it is in fact printed as expected.

Good find @emerald000. I've been looking for why these exist in the AKH set since I saw them in the JSON before release.

**Comment by ZeldaZach** [comment]
The card was printed in the expansion packs (those small decks that are given to new players)  that's why it's # is > set number. It is apart of the set and is legal.
