### ISSUE TITLE
B.F.M. is broken

### ISSUE THREAD

**Issue by KingSupernova31** [mtgjson/mtgjson#356]
The Unglued card B.F.M. is broken. The card object in the JSON file only includes the characteristics of the right half, except it takes the name from the left half. It's a rather unique card, so I don't think it's deserving of its own layout- the object should probably just include the text from the left half as well.

**Comment by Garbee** [comment]
We need both halves. As, you could have one half but not the other.

**Comment by KingSupernova31** [comment]
I'm not sure what you mean by that.

**Comment by Garbee** [comment]
Ideally what we'd do here is BFM Left and BFM Right sides. Have two separate card entities, since, they are two separate cards that are required to be played together. Just like how [Gatherer](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=9844) shows it. It would be kinda like how the split flip cards work as far as data structure.

**Comment by KingSupernova31** [comment]
But then the one on the right would have no name.

**Comment by silasary** [comment]
It would probably be given a name such as "B.F.M (Right side)"

**Comment by bakert** [comment]
Did this get fixed? I see a card in UGL.json with "imageName": "b.f.m. 1" and another with "imageName": "b.f.m. 2". 

They both have:

```
"name": "B.F.M. (Big Furry Monster)",
      "names": [
        "B.F.M. (Big Furry Monster)",
        "B.F.M. (Big Furry Monster)"
      ]
```

The flavor text, oracle text, multiverseid, etc. are all different. Not quite the fix suggested but maybe what we have here is good enough to close this ticket?

**Comment by ZeldaZach** [comment]
I believe it's fixed in v4
