### ISSUE TITLE
Astral Cards from Shandalar?

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#397]
So here's an idea. [There was this one extra game with extra cards](https://magic.wizards.com/en/articles/archive/feature/astral-cards-2009-02-12). Maybe they could be an extra set?

A lot of non-playable sets like HHO are included. Not sure if this is too silly or not.

**Comment by ZeldaZach** [comment]
On the backlog of upstream. If they're not available by the next major release I'll look at doing it manually.

**Comment by ancestral** [comment]
I’m not so sure this is a good idea. The cards aren’t in Gatherer and don’t exist in physical form, and the game is barely available or easily playable on modern computers today, so it’s as if they don’t exist.

On top of that, the Astral cards don’t have up-to-date templating or errata (“play X random fast effects”) and the images are hard to come by.

By that measure, if you decide to include these cards, then you’d have to consider [the Sega Dreamcast Magic game](https://mtg.gamepedia.com/Magic:_The_Gathering_(Dreamcast)). Again, none of these cards were designed by Wizards, and consequently, none of them are recognized by Wizards of the Coast.

**Comment by taw** [comment]
mtgjson already has a lot of cards with no legal paper version.
It's more or less these: https://mtg.wtf/card?q=-in%3Apaper

**Comment by ancestral** [comment]
I think the biggest difference is Wizards actually designed those.

**Comment by taw** [comment]
You're sure they weren't designed by Wizards?

[Also fun fact](https://magic.wizards.com/en/articles/archive/feature/astral-cards-2009-02-12):

> _Now, we said that these cards were created strictly for use in the MicroProse game, but that isn't entirely true. Aswan Jaguar was made as an oversized 6"x9" card, which means that if you're putting together an oversized deck, you can feel free to play it._

[It was printed by Wizards, and has Wizards copyright on it](https://www.ebay.co.uk/itm/Aswan-Jaguar-Jumbo-Oversized-6X9-Arena-Promo-Card-MTG-Magic-Hot-Sexy-Pimp-OOP/323283864519?hash=item4b45384bc7:g:nBkAAOSwRNRbEdmo).

**Comment by omfgitsmark** [comment]
Shandalar is one of my favorite games of all time, I highly support this idea. I actually have the game installed on my PC right now, so saying "...the game is barely available or easily playable on modern computers today..." is pretty inaccurate. There's actually a pretty big community that keeps the game updated for modern computers and more, so it's actually prevalent and pretty easy to find.

P.S. Ancestral, it actually lets you play draft/sealed tournaments against bots with the old cards, so maybe you should try it :grin:

**Comment by ancestral** [comment]
>It was printed by Wizards, and has Wizards copyright on it.

That's a little misleading. It was an oversized promo card for the game.

I’m only saying we need to be careful with these [because there are some weird “cards” out there](http://www.magiclibrarities.net/444-rarities-microprose-computer-game-cards-english-cards-development.html#card018) — if you can call them that. There is no up-to-date errata, and in the case of the SEGA cards, they’ve never had a formal English translation. Wizards even says this:

>They're not "real" Magic cards, but they have sort of a shadowy half-existence.

(And taw, that’s a light-hearted tone at the end of the article about the oversized cards. Because people don’t play entire decks of oversized cards, that’s intended as a joke.)

Keep in mind these not real Magic cards are usable in 0 paper formats and 0 digital formats. If, however, people are *still* keen on including third-party cards into MTGJSON, then it might be worth consideration to not have them in the “allcards” file.

**Comment by omfgitsmark** [comment]
I feel like I should note, originally the fact that I love the Shandalar game(s) I was a bit blinded by nostalgia and my opinion was clearly bias. After consideration, @ancestral makes valid points and I completely understand his position against adding these cards. So I am going to rescind my support for this and abstain from agreeing or disagreeing; I stand mute. _Let the chips fall where they may._

However, there may be a feature here for the future, possibly a `SupplementalCards` or `AuxiliaryCards` download option that includes any historical cards that don't quite fit into the traditional definition of a "Magic card". Although, I understand there's not really a great place to grab this data from, along with other pitfalls of creating such a download. **I would definitely help in compiling these.**

_P.S. I still think everyone should play Shandalar because it's awesome! I'll even send you a link to the  installer if you really don't feel like Googling it_ :grin:

**Comment by ZeldaZach** [comment]
And we're done :) https://scryfall.com/sets/past
