### ISSUE TITLE
Duplicate card entries in AllSets.json (10E specifically)

### ISSUE THREAD

**Issue by jaikamat** [mtgjson/mtgjson#413]
#### MTGJSON Version: 4.X.X

Version 4.4.2

#### Description of Bug:

After combing through some of the data I noticed that there seem to be duplicate entries for random cards in Tenth Edition such as `Birds of Paradise` and `Ascendant Evincar`. They have matching `tcgplayerPurchaseUrl`'s, yet the first BoP entry has a `multiverseiId` while the second does not. Curious if this is intentional?

**Comment by ZeldaZach** [comment]
This is intentional. If you look at the "duplicate" copies, you'll see an `isAlternative` flag attached to them. This is because 10th Edition foils were different in that they did not have reminder text. This lead to a distinction in the cards that is not normally found. You can also see that the normal version has isFoil=False and the foil ones have isNonFoil=False.

Sorry for the confusion on this one, it's a bit of a nuance.
