### ISSUE TITLE
Cards with Split Layout don't pull full info for each section of the card

### ISSUE THREAD

**Issue by Morioki** [mtgjson/mtgjson#42]
**Describe the bug**
Split cards most recently from the GRN block are not pulling the full data for each section of the card.  For example, the card Invert // Invent is shown as Invert as the base name with both names in the Names entry. It seems both sides split they text and type across Text / OriginalText and Type / OriginalType. 

The issue appears to be in terms of the ManaCost field, it shows the mana cost for the main named card side but does not show the ManaCost for the other side of the card.

```
{
            "artist": "Mathias Kollros",
            "borderColor": "black",
            "colorIdentity": [
                "R",
                "U"
            ],
            "convertedManaCost": 7.0,
            "foreignData": [],
            "frameVersion": "2015",
            "hasFoil": true,
            "hasNonFoil": true,
            "layout": "split",
            "legalities": {
                "future": "Legal"
            },
            "manaCost": "{4}{U}{R}",
            "multiverseId": 452978,
            "name": "Invent",
            "names": [
                "Invert",
                "Invent"
            ],
            "number": "228",
            "originalText": "Switch the power and toughness of each of up to two target creatures.",
            "originalType": "Instant",
            "printings": [
                "GRN"
            ],
            "rarity": "uncommon",
            "rulings": [
                {
                    "date": "2018-09-12",
                    "text": "Invert has received 0-day errata to clarify that the effect lasts only until end of turn. For more information see https://twitter.com/EliShffrn/status/1040006137616072704"
                },
                {
                    "date": "2018-10-05",
                    "text": "If you chose two targets, Invert switches the power and toughness of one creature and it switches the power and toughness of another creature. It doesn’t switch one creature’s power with another creature’s power."
                },
                {
                    "date": "2018-10-05",
                    "text": "Effects that switch a creature’s power and toughness apply after all other effects, regardless of when those effects began to apply. For instance, if you cast Invert targeting a 1/2 creature then give it +2/+0 later in the turn, it’s a 2/3 creature, not a 4/1 creature."
                },
                {
                    "date": "2018-10-05",
                    "text": "While resolving Invent, you could put no cards, an instant card, a sorcery card, or an instant card and a sorcery card into your hand."
                }
            ],
            "subtypes": [],
            "supertypes": [],
            "text": "Search your library for an instant card and/or a sorcery card, reveal them, put them into your hand, then shuffle your library.",
            "type": "Instant",
            "types": [
                "Instant"
            ],
            "uuid": "054a4e4f-8baa-41cf-b24c-d068e8b9a070"
        }
```

**Comment by taw** [comment]
Also cmc is just bad, it should be per side and instead we get total.

**Comment by tooomm** [comment]
Since AKH this is correct (rules wise) if you think about the physical card: 
https://magic.wizards.com/en/articles/archive/news/amonkhet-split-card-rules-changes-2017-04-04

However I definitely see a use case for a per side display.
Especially since information gets lost if only the combined is shown for both. Instead, calculating and displaying the combined value when needed would be easy when the single cmc are known.
Maybe this should be changed for v4 to have all relevant information stored! @ZeldaZach
Right now nobody could search for a split card side by cmc...

**Comment by taw** [comment]
In some contexts cmcs add up, but that happens only sometimes (not on stack), and in any case it's not useful for people searching things.

**Comment by ZeldaZach** [comment]
I've spoken with several peoples and I think I'm going to leave the CMC as-is. I can't think of a proper way to justify each side, as the CMC being marked as 4 is technically wrong when the card's total CMC is 7. 

The originalText/originalType has some issues with split cards, because gatherer parsing is nonsense and impossible to get right. Unfortunately that's a bug that is a long-term goal to fix :(

I'll open a new ticket at some point for the gatherer re-scrape fix

**Comment by fenhl** [comment]
> the CMC being marked as 4 is technically wrong

This is incorrect. To quote the rules:

> **708.3b** While on the stack, only the characteristics of the half being cast exist. The other half’s characteristics are treated as though they didn’t exist.

This means that a half of a split card is, at least sometimes, completely independent of the other half. As such, it makes sense to model the two halves as separate, including a separate CMC. While not on the stack, *all* characteristics of a split card are combined, not just CMC. Let me stress this again: CMC is not special in any way; combining both halves is something the game rules do for *all* values. There are multiple ways to model this:

* Use merged values for all values, as if we were looking at the card in, say, a player's hand. This would make Commit // Memory a single card in the database, with a `"types"` of `["Instant", "Sorcery"]`, for example, and a mana cost of `{7}{U}{U}{U}`. This is bad because we lost information, since it's not possible to reconstruct the mana cost of either half.
* Use separated values for all values, as if the card were on the stack, as was done in v3. This is the most reasonable approach in my opinion.
* Use merged value for CMC, and use separate value, as is the current state of v4. This is inconsistent for no reason, and the only reason it's not that big a problem is that CMC is a derived value; downstream projects can work around this by recalculating it from the mana cost.

**Comment by Fryyyyy** [comment]
I agree that having separate values is best, since it's easy to combine them if you need "full card CMC" and hard to separate out if it's just the total on both sides

**Comment by jhallbachner** [comment]
Practically speaking, although it's technically true that there is a time at which a split card's CMC is only equal to one of the halves (and that is relevant to some card interactions, like being countered by Disdainful Stroke) it's always the combined value when the card is in hand, the library, the graveyard, exile, etc. The closest analogous situation I can think of is X spells, where the reported CMC is also the one that's accurate everywhere besides the stack. As such I feel like the combined value is, under the current rules, the most accurate answer.

**Comment by Fryyyyy** [comment]
This isn't a rules engine, though. It's just some facts about the cards, and each half is listed separately in the file.
It's fairly simple logic to calculate the CMC of a split card using one or both halves if you know which zone the card is located in.

**Comment by ancestral** [comment]
Invert // Invent’s converted mana cost is 7. (This is also how Scryfall does it.)

> 202.3d The converted mana cost of a split card not on the stack or of a fused split spell on the stack is determined from the combined mana costs of its halves. Otherwise, while a split card is on the stack, the converted mana cost of the spell is determined by the mana cost of the half that was chosen to be cast. See rule 708, “Split Cards.”

By definition, the “converted mana cost” of Invert // Invent is the combined mana costs of its halves. The combined *mana costs,* not the combined converted mana costs. This is important: each half does not have an individual converted mana cost. There is currently never a rules interaction that references a half of a split card’s converted mana cost. A half of a card does not have its own converted mana cost. There may be cards that reference the half’s mana cost, and this mana cost is listed in the card.

While the card is on the stack, it may have different qualities, for sure. But while it’s not on the stack, the card has a converted mana cost of 7. Appetite for Brains, Blazing Shoal, Chalice of the Void… these cards need to reference this card’s converted mana cost, which is 7.

**Comment by fenhl** [comment]
~~This is a fair point. We don't model X costs in CMCs either, so this would be consistent.~~

**Comment by fenhl** [comment]
However, my point about consistency with other values of a card still stands. Glittering Wish can find Armed // Dangerous, yet we do not set Armed's colors to `["R", "G"]`.

**Comment by ancestral** [comment]
Perhaps the color should be that of the combined halves then?

**Comment by fenhl** [comment]
And the mana cost, and the rules text, etc.?

**Comment by ancestral** [comment]
Hmm. The split card is the combined characteristics of both halves, and each half has its own characteristics (mana cost, color, rules, etc.). In the example from the original issue, the converted mana cost is the combined mana costs, but each half doesn’t have a converted mana cost as that’s a card’s characteristic, not a card’s half’s characteristic.

So the correct answer is probably not putting a converted mana cost for either half, since the converted mana cost is not a single half’s characteristic.

**Comment by Psithief** [comment]
The problem is that you are confusing card properties with spell properties.

A split card has a set of card properties, and a split card also represents two (or more - in silver border) spells, that are themselves objects with their own properties such as converted mana cost. Spells, of course, only exist on the stack. At all other times, a card has its card properties instead of spell properties.

So really the spells should be nested in a card object (Armed // Dangerous) as a two-long array (the Armed spell and the Dangerous spell), where the card has a CMC property, and each spell also has its own CMC property. The same for colours, text, types et cetera et cetera.
For every non-split card spell there's an implicit self-reference from the card's spell property to the card itself, though whether you want to make an exception for spells with an X in the casting cost is up to you.
Are you using JSON with references?

**Comment by taw** [comment]
I feel that mtg.wtf index has a lot more clarity around such concepts with Card, CardPrinting, PhysicalCard etc (except for meld, I hate that mechanic and how it messes up with otherwise perfect domain model)

**Comment by ancestral** [comment]
>So really the spells should be nested in a card object (Armed // Dangerous) as a two-long array (the Armed spell and the Dangerous spell), where the card has a CMC property, and each spell also has its own CMC property. The same for colours, text, types et cetera et cetera.

Yes, except it is important to know that CMC is not a property of a card half, it is the property of a card. Individual halves do not have separate CMCs.

**Comment by Psithief** [comment]
> > So really the spells should be nested in a card object (Armed // Dangerous) as a two-long array (the Armed spell and the Dangerous spell), where the card has a CMC property, and each spell also has its own CMC property. The same for colours, text, types et cetera et cetera.
> 
> Yes, except it is important to know that CMC is not a property of a card half, it is the property of a card. Individual halves do not have separate CMCs.

This is incorrect. I was not inventing such a thing as a "card half". I was adding _spells_. If `Gaddock Teeg` (`Noncreature spells with converted mana cost 4 or greater can't be cast.`) is on the battlefield then `Beck` from `Beck // Call` could be cast, but `Call` could not.

`Beck` is a spell, nothing can ever see the spell exists unless it's being cast or on the stack. At all other times, it merely, quietly contributes its properties to those of the card `Beck // Call`.

**Comment by ancestral** [comment]
>If Gaddock Teeg (Noncreature spells with converted mana cost 4 or greater can't be cast.) is on the battlefield then Beck from Beck // Call could be cast, but Call could not.

True, when the card is on the stack it behaves differently than when in your hand. It changes as/after it’s cast.

The point I’m trying to make is whichever half you refer to doesn’t have a cmc before it’s cast.

**Comment by KingSupernova31** [comment]
The way the rules of the game handle split cards really isn't important, because there can be applications that care about a detail of split cards that the rules of the game don't. However just to clear up several incorrect statements about the rules that have been made in this thread: A split card in any zone other than the stack has the characteristics of both halves. So for example, a Wear // Tear in the library has CMC 3, mana cost "{1}{R}{W}", text "Destroy target artifact./nDestroy target Enchantment" etc. While on the stack it has only the characteristics of the half that was cast, so if you cast Wear: CMC 2, mana cost "{1}{R}", text "Destroy target artifact.", etc.

The current handling is most certainly not correct. It looks like colorIdentity and convertedManaCost are being combined from both sides, while all other fields are calculated individually. This is inconsistent and removes access to data that might be needed. All fields should be calculated individually like they were in v3, and the application can always combine the two if it needs to.

As an example, the website I maintain needs to be able to tell what the CMC of individual halves are in order to include them properly in search results, so I won't be able to move from v3 to v4 until this is fixed.

**Comment by ZeldaZach** [comment]
Closing in favor of individual tickets with these issues listed out
