### ISSUE TITLE
Missing legalities for MTG Arena Best of One.

### ISSUE THREAD

**Issue by harbingerofme** [mtgjson/mtgjson#431]
#### Description of Bug:
[Nexus of Fate is banned in MTGA best of one formats. ](https://magic.wizards.com/en/articles/archive/news/mtg-arena-banned-and-restricted-announcement-2019-02-14) This is not reflected in the mtgjson.

**Comment by ZeldaZach** [comment]
I'd consider making a change, but since it rotates in a few weeks I'm inclined to no-fix. We also don't support BO1 currently.

**Comment by Nicate** [comment]
Be advised that when the format rotates, Arena will introduce an additional format called Historic, in which presumably Nexus of Fate will still be banned for Bo1 (it was banned since it could essentially stall the game for half an hour). How they will choose to term that I don't know, since I'm guessing you can probably also play best-of-three in this format.

It may also be possible that bans like Rampaging Fericodons will carry on into this format, but only time can tell.

**Comment by ZeldaZach** [comment]
If that happens we will re address
