### ISSUE TITLE
SetList.json does not contain block, as indicated by the changelog

### ISSUE THREAD

**Issue by ericcholis** [mtgjson/mtgjson#453]
http://mtgjson.com/json/SetList.json Does not reflect the changes listed in the changelog, is missing the block field.

**Comment by KMontag42** [comment]
I am not sure if the code was released to production yet? I noticed this as well.

Happy to debug as necessary!

**Comment by fenhl** [comment]
Since it's on the changelog, it should be in production.

**Comment by KMontag42** [comment]
When I `ctrl+F` through the page, and search for `block` I do in fact see that it is there.

```json
  {
    "name": "Zendikar",
    "code": "ZEN",
    "releaseDate": "2009-10-02",
    "block": "Zendikar"
  },
  {
    "name": "Worldwake",
    "code": "WWK",
    "releaseDate": "2010-02-05",
    "block": "Zendikar"
  },
```

Since many of the sets in MTG live outside of the Block system, there will be lots of them without the relevant information.

Are there sets in particular that you have found to be missing information? If so, you can submit a PR to update their information, `SetList.json` pulls its block information from the static information about each set in the repo.

Hope this was helpful.

**Comment by KMontag42** [comment]
@fenhl I would call this closed since the data is in fact there.

**Comment by fenhl** [comment]
Agreed.
