### ISSUE TITLE
Don't fail quite so hard/early if we can't parse a page

### ISSUE THREAD

**Issue by bakert** [mtgjson/mtgjson#482]
When running a large rebuild we sometimes fail to get a sensible version of a page from Gatherer which then kills the entire process with an exception.

I see:

    Error: multiverseid [20224] cardParts length [1] does not equal printedCardParts length [0]
    oracle url: http://gatherer.wizards.com/Pages/Card/Details.aspx?
    multiverseid=20224&printed=false
    printed url: http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=20224&printed=true
        at Function.processDefaultDoc (/Users/bakert/mtgjson/build/rip.js:563:11)

occasionally for any random card.

I can then fix this pretty easily with:

    $ node util/clearCacheForSet.js all {set code}

and re-run. But in the mean time the (lengthy) process has not been continuing.

It would be good to (a) check page size is sane and apply the retrying logic if not and (maybe) (b) retry on any error in parsing at least once before giving up, not just complete failure to download.

**Comment by gwax** [comment]
This tends to happen because Gatherer is really flaky and doesn't report errors very well. You'll get an http response 200 (success) with a half loaded page that sometimes contains text about having an error. Other times it'll just partially load and not tell you much of anything until you get this error.

It happens randomly enough that I wasn't able to develop a reasonable heuristic for catching it.

It would be great if we could collect Gatherer failures that cause this and fix them when we can.

I've also thought that some sort of pre-fetch option to download everything and then process later might be a nice way to work around how long it takes to get an initial batch of data.

**Comment by ZeldaZach** [comment]
Not too relevant for v4 now
