### ISSUE TITLE
Star (★) and Asterisk (*) used interchangeably

### ISSUE THREAD

**Issue by ancestral** [mtgjson/mtgjson#497]
#### Description of Bug:
Cards are using star (★) and asterisk (*) interchangeably for fields. For example, the Fish // Kraken DFC token is using a star for the card number, whereas other cards are using * for power.

I think some consistency would be welcome across fields that reference stars. * seems like a safer bet for all fields that want to represent stars.

**Comment by ZeldaZach** [comment]
_technically_ they're different. You can clearly see that P/T use asterisks vs card numbers that use a star icon. I'm not feeling inclined to change this right now. If you'd like to discuss this point further, do post!

**Comment by ancestral** [comment]
But they’re stars on both parts of the card, in real life. Why have a harder-to-type Unicode symbol in the card number?

**Comment by ZeldaZach** [comment]
This makes sense to me. I took a look and it seems the stars are arbitrary. Will convert.

**Comment by cheyner** [comment]
I've gotten tripped up by this myself.  Because set number is routinely used by us (and others) as part of URL slugs, I'd vote for something more URL-friendly like "P".

**Comment by kodawah** [comment]
i also run into this but i believe it's better to keep information from cards as printed, instead of introducing yet another standard.. that means surgical extraction gets * and emrakul gets (star)

also, what wrong of having the star in the link, it's not anybody is typing them out, and browsers support the string conversion correctly https://scryfall.com/card/proe/%E2%98%854/emrakul-the-aeons-torn

**Comment by ZeldaZach** [comment]
@kodabb brings up a good point. Why change what many other sources are following? I want to keep data interchangeable if possible. This can be converted on the end user's side. We should make a note about the use cases.

cc: @staghouse
