### ISSUE TITLE
Better german translations

### ISSUE THREAD

**Issue by DJCatBlitz** [mtgjson/mtgjson#562]
Hi Zach!
My son complained that he does not understand all the english cards, so I changed my Magic software to use german cards using your files.
I had a few major problems:
- around 1000 cards are not translated
- for many cards AllPrintings does not contain the most current translation
- MANY translation are really bad, because they contradict the current rule set
- subtypes are not changed, when english cards are changed
- many typos

So I started to translate every card (and inventing new card names if they do not exist), fixed all translations to use current wording and streamlined the translations to use the same templates for effects.
Are you interested in using them as a source for german translations in mtgjson?

[Translations_de.zip](https://github.com/mtgjson/mtgjson/files/4620449/Translations_de.zip)

**Comment by ZeldaZach** [comment]
Hey @DJCatBlitz thanks for taking the time to do this! While I want to address foreign cards better, I don't think I can do much with your translations at the moment. The issue is Wizards provides official translations for cards. While they struggle to update foreign translations, we don't have a great way to validate 3rd party translations right now. I think this was a great learning project for your son to continue playing magic.

I can try proposing this change upstream, but I'm not sure if they're too interested in it at the moment. Again, thanks for being awesome and helping the project! :)

**Comment by DJCatBlitz** [comment]
OK L

You are right, that Wizard provides translations, but they don’t do it for at least 1100 older cards. So I thought this would be nice for foreign players to have translations for them.

 

Von: Zach H [mailto:notifications@github.com] 
Gesendet: Sonntag, 7. Juni 2020 05:36
An: mtgjson/mtgjson
Cc: DJCatBlitz; Mention
Betreff: Re: [mtgjson/mtgjson] Better german translations (#562)

 

Hey @DJCatBlitz <https://github.com/DJCatBlitz>  thanks for taking the time to do this! While I want to address foreign cards better, I don't think I can do much with your translations at the moment. The issue is Wizards provides official translations for cards. While they struggle to update foreign translations, we don't have a great way to validate 3rd party translations right now. I think this was a great learning project for your son to continue playing magic.

I can try proposing this change upstream, but I'm not sure if they're too interested in it at the moment. Again, thanks for being awesome and helping the project! :)
