### ISSUE TITLE
All Battlebond partner cards are duplicated, with bogus numbers, and with questionable names

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#586]
Check https://mtgjson.com/json/BBD-x.json

Find for example "Regna, the Redeemer" and "Krav, the Unredeemed". They both appear twice with bogus numbers 3a/3b, and 4a/4b - while each is really just once with numbers 3 / 4.

This affects every single partner card.

Rowan Kenrith / Will Kenrith is affected worse due to their alt art version, but fix below works as well.

There's somewhat related issue that `names` field which generally is used for parts of the same card is used for partners, and it seriously shouldn't.

[mtg.wtf adds extra `related:` field by regexping cards mentioning names of other cards](http://mtg.wtf/card?q=related%3A*) and this fancy technology should probably be copied over to mtgjson.

As far as I can tell the fix is simply:

* delete all cards with `b` in number
* remove all `a` from numbers
* remove all `names` fields

**Comment by ZeldaZach** [comment]
The way they did partners in this set mimics how flip cards were established in prior sets. A simple set flag is necessary to deal with this, which will happen in v4

**Comment by magreenblatt** [comment]
The duplicate card entries mentioned above have the same "multiverseid" value. For example, there are 4 "Rowan Kenrith" records with the 445970 multiverseid and 2 "Zndrsplt, Eye of Wisdom" records with the 445973 multiverseid. The "number" and "imageName" suffixes change for the duplicate records but they are otherwise the same. The first instance of each record will have the "a" suffix on "number" and the remaining records will have the "b" suffix. So, an alternate fix would be to only keep the first record for any given multiverseid, and then delete the "names" field and the "number" suffix for that record.

In addition to the problems already mentioned "Zndrsplt, Eye of Wisdom" and "Okaun, Eye of Chaos" are incorrectly marked as "flip" layout.

**Comment by ZeldaZach** [comment]
This should be fixed in V4's latest beta build.
