### ISSUE TITLE
isShandalar

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#587]
So now that we have Shandalar cards in PAST set, maybe we could have `isShandalar` in addition to `isArena`, `isMtgo`, and `isPaper`?

[There are some lists like this one](http://www3.sympatico.ca/eleibrock/Magic/Shandalar/Shandalar.htm). Of course this leads to question which edition is that from.

**Comment by silasary** [comment]
> after the Duels of the Planeswalkers and Spells of the Ancients add-ons have been applied.

**Comment by ZeldaZach** [comment]
Hmm, I see Scryfall supports "astral" as a game type for those 12 cards in PAST. This could be expanded out to those cards on the list you provided, Taw. Maybe this is an enhancement upstream can do? cc: @csuhta

**Comment by csuhta** [comment]
`astral` is the same as `shandalar`, we use `"astral"` because that seems to be [how WotC chooses to refer to these cards / this game](https://magic.wizards.com/en/articles/archive/feature/astral-cards-2009-02-12). (The game is officially just called "Magic: The Gathering", so these different identifiers are all community-driven for the most part)

We also have `"sega"` as a game value now too: https://scryfall.com/sets/psdg

**Comment by ZeldaZach** [comment]
Do you plan on supporting the `astral` tag for more than just the 12 cards in PAST? Such as https://scryfall.com/card/arn/1/abu-jafar
