### ISSUE TITLE
v5 foreign flavor names are weird

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#611]
So not sure what to do with this:

```
      "flavorName": "Mechagodzilla, the Weapon",
      "foreignData": [
        {
          "language": "Japanese",
          "name": "結晶の巨人 (決戦兵器、メカゴジラ) // Mechagodzilla, the Weapon",
          "text": "あなたのターンの戦闘の開始時に、飛行、先制攻撃、接死、呪禁、絆魂、威迫、到達、トランプル、警戒、＋１/＋１の中から、結晶の巨人の上に置かれていないカウンター１種類を無作為に選ぶ。結晶の巨人の上に、その種類のカウンターを１個置く。",
          "type": "アーティファクト・クリーチャー — 巨人"
        }
      ],
```

There's no English text on that card. `flavorName` is `結晶の巨人`, official `name` is `決戦兵器、メカゴジラ`.

Affected cards seem to be:
* "結晶の巨人 (決戦兵器、メカゴジラ) // Mechagodzilla, the Weapon"
* "哀歌コウモリ (暗黒破壊獣、バトラ) // Battra, Dark Destroyer"
* "不思議な卵 (モスラの巨大な繭) // Mothra's Great Cocoon"

**Comment by ZeldaZach** [comment]
This appears to be a limitation that Wizards only published these cards in Japanese, and upstream providers are only showing English names for the split. 

cc: @csuhta

**Comment by csuhta** [comment]
For these specific cards, we have it formatted like this currently because we lack a field for what WotC has done here.

These cards have four title texts:

- Oracle name
- Localized name
- Localized flavor name
- WotC also published the English version of the localized flavor name, and people want to search by it, and we don't have a distinct field for this problem just yet
