### ISSUE TITLE
Legalities should return false values instead of being omitted

### ISSUE THREAD

**Issue by staghouse** [mtgjson/mtgjson#639]
Right now legalities on a card can return no properties if they are not legal. Instead they should return false.

For example. Sol Ring

"modern": false

**Comment by tpblaster** [comment]
I think it makes more sense to return False only for banned cards in a format. Cards that are not legal because they have not been printed in a modern set should return no properties.

**Comment by kodawah** [comment]
I don't think it's correct to expose something like that, listing all the formats everywhere would be wasted space and a bit of a maintenance burden when new formats are issued

Legalities are boolean values, a card can either be legal or illegal in any given format, so mtgjson sets a `flag`->`true` if it's legal, or does not set anything if it's illegal: there is no "third state" that a missing flag could convey or be confused with. Besides, all json parsers already deserialize `null` (missing object) to `false` with no extra code

**Comment by staghouse** [comment]
I think returning SOMETHING is better than nothing. Empty string makes sense to me since the false is not very semantic and null is often returned as false.

**Comment by kodawah** [comment]
returning nothing for false boolean values is very common in json

**Comment by ZeldaZach** [comment]
I'm inclined to close this as a no-fix because omitted values are commonly known as NULL/FALSE in JSON.

In this situation, if a value is not found, it can be inferred that the card is not allowed to be play in that specific format. If a value is found, you can check with that value if the card is allowed or not.

If the documentation on this isn't clear, we should rectify that. I'm not set on making a code change at this time though.
