### ISSUE TITLE
smaller allprices.json file for daily price data

### ISSUE THREAD

**Issue by kodawah** [mtgjson/mtgjson#673]
instead of downloading a huge (maybe compressed) file containing several days worth of data, it might be interesting to prive an abridged version containing only today's prices

while an xdelta will cover that in the future a lot of sites tracking prices have their own way of managing history, and do not need the backlog, saving gigabites of downloads over time, and using more than half less memory while operating on the file

**Comment by ZeldaZach** [comment]
I don't think I'm going to be providing a new compiled file with _just_ today's pricing, as #634 will solve this with a patch. If a user wants access to the latest prices from today right away, why can't they poll the appropriate APIs from those services?

Leaving open for a bit for discussion, but I'm considering this a dupe

**Comment by kodawah** [comment]
because access to those services is often guarded via API access, and API limiting, while a single point of access to a bunch of data is one of the strongest features or mtgjson (besides the fact that users needs to translate those services entries into mtgjson's to be usable)

**Comment by kodawah** [comment]
besides, the uncompress file with 3 stores is like 500MB, with a few more stores it'll get to 1GB easily.
Do you really want to churn that much data every day in user downloads? Even with xdelta, I believe the diff is going to be pretty big in my opinion, and on the user side, it's much much better to deal with smaller files anyway

**Comment by peardox** [comment]
ATM AllPrices.json is one exceedingly long line of data. If the file was one line per record then processing it would be far easier.

e.g.

{
  "data": {
     "00010d56-fe38-5e35-8aed-518019aa36a5": {...}, 
     "0001e0d0-2dcd-5640-aadc-a84765cf5fc9": {...}, 
           ----- c. 53k similar lines -----
     "0003caab-9ff5-5d1a-bc06-976dd0457f19": {...}
    },     
  "meta": { "date": "2020-09-08", "version": "5.0.1+20200908" }
}

Each price record now averages 8k and can be read in for processing using the readline method/function of your favourite language. Each line can be treated as a separate piece of JSON merely by removing the comma at the end of the record (if present) and wrapping the resultant text in braces to create a valid JSON object again.

The memory required to process the data is now based on whatever the longest record length length is

This will add 53k-106k (depending on line endings) to the uncompressed filesize (0.022%)

Oh - why is meta at the end? If it was at the start you could tell if you'd already had it very quickly...

**Comment by peardox** [comment]
Oh. forgot to mention...

I'll write a cross-platform native code (i.e. compiled) extractor to - err - extract the data you're after. Most useful option would be most recent price although I can make other options available as well if requested

**Comment by st-sha** [comment]
@peardox I am pretty interested in daily data that doesn't require JSON parsing to narrow it down. Have you made any headway on the extractor?

**Comment by peardox** [comment]
@anawis Yep, Lots. My current model is two end-product tables (with a fair few intermediate ones) that boil everything down to two MySQL tables for my own specific uses.

The prices stuff I create a pricegrid of one row per uid with 14 fields - the uid, a timestamp + 3 x 4 lots of prices (only interested in paper). This is probably what you want.

This price table links to a cards table called uuids that has the essential data per card - this is limited to very basic info per card (name, typeline, rarity, scryfall ref etc).

The tables are as follows...

pricegrid - 51220 rows of 14 fields
uuids - 58169 rows of 16 fields - 57346 cards + 823 backs / alternate card representation (e.g. adventure has two records per card)

There are less entries in pricegrid than uuids 'cos only 89.5% of the cards have prices

The stuff is generated whenever AllPrices is updated (I check the last modified time for AllPrices.json once an hour). When there's a new version the new AllPrices is processed into an intermediate set of tables that are then further distilled into pricegrid - then it emails me to say it's done. This has been running flawlessly since September 2020 - takes about an hour to run on my £6/m server.

The uuids stuff is generated by a Free Pascal (runs on everything) program - https://github.com/peardox/MTGADownloader This one downloads all the set json files then uses those to create a CSV of the data for the uuids table and optionally get a local copy of all new card images (this is immenently being improved to include scryfall CDN image URLs - just waiting for some code from a colleague)

It should be noted that these are both evolving as I want them to - see http://decknet.co.uk for a current very basic test page (I'm changing that ATM too - order is temp wrong cos of image dates)

If you want copies of anything that sounds useful lemme know and I'll sort you out

Other URLs for test page
https://decknet.co.uk/?set=eld
https://decknet.co.uk/?set=znr (Sorting is wrong ATM... I'm playing with it)
https://decknet.co.uk/?set=znr&ord=num (Proper version of above)
https://decknet.co.uk/?set=khm&ord=num

**Comment by dgant** [comment]
Would 😍 to see this go forward. At almost 1GB AllPrices.json exceeds the memory of ComboDeck's cloud instance.
