### ISSUE TITLE
add CollectorNumbers array to each card object

### ISSUE THREAD

**Issue by kodawah** [mtgjson/mtgjson#706]
Similar to Printings, this array should contain the collector numbers of the card as printed in same edition.
This should facilitate listing all the possible variations as the Variation array doesn't contain the original uuid

**Comment by ZeldaZach** [comment]
Just trying to understand this a bit more. The variations field intentionally doesn't include a self reference.

Set Foo with CardA printed 3 times (Denoted CardA1, CardA2, CardA3) should give enough information to link around.

```
CardA1 {variations: [CardA2.uuid, CardA3.uuid]}
CardA2 {variations: [CardA1.uuid, CardA3.uuid]}
CardA3 {variations: [CardA1.uuid, CardA2.uuid]}
```

What would adding the collector number to this sequence add that the UUID doesn't?

**Comment by kodawah** [comment]
two things are missing

1. the variations array does not contain the id of itself - this is understandable but in that case if you want to print all numbers of a card in a set you need additional logic to print the card itself, then print all the other variations. This is different from Printings where the SetCode of each card is printed, every time
2. the order is impacted, Printings allows for a stable sorting of all the printed editions, while if one were to implement (1) the order would not be predictable (or efficiently sort-able) depending on which card is being queried

maybe these points could be solved by adding the card uuid to the array itself? it's still some extra work than just printing an array, but maybe it's fine, what do you think?

**Comment by ZeldaZach** [comment]
Since you'd have to iterate the entire card list in a set anyway, A card collector number array just duplicates this field and wouldn't make the search that much easier. I suppose you could binary search into the set with a collector number, as we guarantee ordering of the objects by collector number, but most sets have ~500 (With Jumpstart being the max at ~800), so this lookup as O(N) vs O(LgN) wouldn't be that big of a difference.
