### ISSUE TITLE
Card type array for some older cards contains bad values

### ISSUE THREAD

**Issue by ChainsawXIV** [mtgjson/mtgjson#710]
#### Version(s) affected
- [x] MTGJSON 4
- [x] MTGJSON 5

#### Version(s) tested against
MTGJSON 5.0.1 API data as of 2020-11-07
Issue has been present since at least 2020-07-04

#### Description of Bug
The array of card types for some cards contains incorrect data which appears to have been parsed from the original 1990s style type lines for the cards.

For example, the types array for the card Prismatic Dragon is ["Summon", "Dragon"]. The card's subtype array is empty, and "Creature" does not appear in its type array.

This appears to affect primarily or exclusively older MTGO exclusive cards which are not listed in Gatherer, and is thus likely to be a problem coming from wherever that card data is sourced.

**Comment by ZeldaZach** [comment]
This might be unintuitive, but this is working as expected. The card you're referring to is from [Astral Magic aka Shandalar](https://magic.wizards.com/en/articles/archive/feature/astral-cards-2009-02-12), which has several cards never seen since. These cards were never "real" in the sense of being collectable in any fashion. As such, they never received Oracle updates and we elected to keep the original options for these cards. 

You can understand these cards aren't "real" by the `availability` param, which for these cards indicates "shandalar" as their only availability. 

If you find we need a better process to identify "real" Magic cards versus relics of the past, I'm all ears. But for now, this seems to function as I have intended.

**Comment by ChainsawXIV** [comment]
Thanks for the clarification.

Real vs. relics isn't really an issue for my application of the data, so much as having the relics pollute the user experience with data that looks wrong to the end user (in this case, the types from a filtered list of cards are gathered into the UI and used, and my users thought there was some kind of bleed-over from the subtypes and reported it as a bug to me).

This feels like a "no right answers" scenario to me - on one hand, you're doing the most technically correct thing here, and putting each word from the card type into the data, rather than making any judgement calls about what the data should look like, but on the other hand the result of that process defies user expectations (setting aside the UI implications of my specific use case, this means there are creatures that don't come up when you filter for the creature card type, for example, which is just... wrong, rationally).

Resolving this requires the data be transformed to conform to the mechanics of the game rather than the printing on the cardboard, and if I'm the only one impacted then it should be me to does that for my own version of the data set I suppose. But I'd be surprised if I'm the only one impacted, and this might be a case where both the printed and interpreted versions of the data are relevant to different use cases.
