### ISSUE TITLE
Type-changing CDAs are not taken into account

### ISSUE THREAD

**Issue by KingSupernova31** [mtgjson/mtgjson#756]
MTGJSON fails to considers characteristic-defining abilities that modify a card's subtypes. Tajuru Paragon's subtypes are only Elf, not the other 4 types.

**Comment by ZeldaZach** [comment]
I'm not 100% sold on this being a MTGJSON issue. Since Wizards didn't include this data on the type line, it's a bit in-genuine for me to alter the data to account for data in the card's body.

This feels like a project-specific use case, but I'm open to other opinions on the topic.

**Comment by KingSupernova31** [comment]
It's definitely an MTGJSON issue, it's inconsistent with how you treat other cards. You do take into account the CDA on Ghostfire making it colorless, for example. Either taking into account all CDAs or taking into account none of them would both be reasonable approaches, but doing a rather arbitrary half and half is confusing and leads to inconsistent results.

I think taking all CDAs (and color indicators) into account would be the best solution because the resulting characteristics are the "true" ones for all gameplay and deckbuilding purposes, but ignoring all CDAs would at least be a self-consistent approach.

**Comment by ZeldaZach** [comment]
After talking with several folks, I've decided against this issue. If we added support for Tajuru Paragon to have extra components in its type line, we'd then set a weird precedent that we have to analyze card text to set visible attributes. For example, we'd have to add _every_ creature type to the type line for Changelings, which gets super awkward. A card's types and its type line are not necessarily the same thing, and have to be handled by the end user.

Ghostfire (along with Devoid cards) are exceptions because "color" and "color identity" of the card aren't necessarily apparent and have to be inferred/derived.

Hope this clears the issue up!
