### ISSUE TITLE
Inconsistency in how 10th edition cards represent having a foil version

### ISSUE THREAD

**Issue by Fyzxs** [mtgjson/mtgjson#761]
#### Version(s) affected
- [ ] MTGJSON 4
- [x] MTGJSON 5

#### Version(s) tested against
5.1.0+20210201

#### Description of Bug
125 of the 383 cards in 10th Edition have their foil versions as variations instead of using the `hasFoil` flag.

Example card: `Ancestor's Chosen`  from 10E Set JSON
```
"meta": {
    "date": "2021-02-01",
    "version": "5.1.0+20210201"
  },
  "data": {
 ...
        "hasFoil": false,
        "hasNonFoil": true,
        "identifiers": {
...
          "mtgoFoilId": "27501",
...
        },
...
        "name": "Ancestor's Chosen",
...
        "uuid": "5f8287b1-5bb6-5f4c-ad17-316a40d5bb0c",
        "variations": [
          "b7c19924-b4bf-56fc-aa73-f586e940bd42"
        ]
```

The inconsistency makes the data hard to accurately consume.
The 125 UUIDs for 10th I found with this are in the attached file.
[TenthEditionUuidsWithThisCondition.txt](https://github.com/mtgjson/mtgjson/files/5932269/TenthEditionUuidsWithThisCondition.txt)

**Comment by ZeldaZach** [comment]
Hey @Fyzxs thanks for the ticket. I know it might be weird, but this is intentional behavior. In 10th edition, they played around with the concept of "foil cards have different printed text" via removing reminder text. As such, the foil and non-foil variants are technically different objects. They seem to have backed away from this concept, but in 2007 they [thought it was a good idea](https://magic.wizards.com/en/articles/archive/premium-foils-tenth-edition-2007-07-12).
