### ISSUE TITLE
Add Magic Card Market set names for each set

### ISSUE THREAD

**Issue by KingSupernova31** [mtgjson/mtgjson#78]
Adding the set name used by https://www.magiccardmarket.eu/Expansions would allow those that use the MTGJSON data to more easily integrate into the pricing data provided by that site.

https://github.com/mtgjson/mtgjson/issues/67

**Comment by ZeldaZach** [comment]
I recently got access to TCGPlayer API and pricing system, so I'd consider that before MKM. We're also not really a pricing system, so I'm not sure if I want to go forward with this.

**Comment by fenhl** [comment]
If we're going to implement TCGPlayer IDs, we should also implement MKM IDs. MKM is the only reliable source of Euro prices since the secondary market often looks very different over here.

**Comment by ZeldaZach** [comment]
Fair enough, I'll look into it at some point in the future. This is a lower priority for me at the moment

**Comment by ancestral** [comment]
I feel like we should not be including this sort of thing.

Personally I feel like being pure to the data has value. Given we get the data from Scryfall, and argument can be made to keep some of those data points. Otherwise, it ends up being more steps to keep up-to-date with other services that may come and go.

**Comment by ZeldaZach** [comment]
@ancestral We're talking about major components to the community, not minor one man shows (except mtgjson of course _haha_...). Including MKM/TCG Seems logical to me as they are broad seller markets. Including specific stores I would prob be against

Scryfall provides purchase URLs for tcgplayer/MKM, so it would be a simple parse. It would be up to SF to keep such data up to date from what it looks like. This seems doable

**Comment by ancestral** [comment]
What’s going to happen is you’re going to get requests for CardKingdom, for MTGGoldfish, for ChannelFireball, coolstuff, PucaTrade… where do you end this?

**Comment by nhrsn** [comment]
All other services should be ~bending to the will~ using the IDs provided by mtgjson. I think adding the IDs used by external sites just encourages more inconsistency across all the MTG services out there.

**Comment by ZeldaZach** [comment]
I felt that adding TCGPlayer's id system was appropriate because they have a catered to API network, and we're giving help to those who might want to list and not have to do some grunt work.

If other services provide similar things I'd be willing to consider it, but otherwise I have no further intentions to add additional ID key sets

**Comment by tooomm** [comment]
MKM has an api as well: https://www.mkmapi.eu/ws/documentation
I didn't look into details...
