### ISSUE TITLE
Missing cards in STX

### ISSUE THREAD

**Issue by fverdoja** [mtgjson/mtgjson#789]
#### Version(s) tested against
MTGJSON v5.1.0+20210414

#### Description of Bug
In the STX booster there are these card ids (in the `nonlessonRareMythic` sheet) which do not appear in the card list:
```
2cb11068-280b-55c5-9a74-a638357a1afa
301c7114-6835-5b51-b423-6927b4b09097
```
Maybe related to #784
Maybe of interest of @taw

**Comment by fverdoja** [comment]
After a bit of reverse engineering, it seems to me the two card ids should correspond to:
```
 20 Leonin Lightscribe
151 Jadzi, Oracle of Arcavios 
```

**Comment by taw** [comment]
Here's the visualizer, it always matches latest data, even before it gets to mtgjson: https://mtg.wtf/pack/stx

Anyway two most common issues:

* Most times new set comes out, mtgjson uuids for a few cards will change. Due to the way we update things, if uuid changes, mtgjson's card sheet data will contain old uuid for whole week. That's probably what affected cards 20/151, as I can definitely see them in the visualizer.
* Support for showcase and such cards in boosters is very limited. Only IKO really has it implemented. That's because every set does this just a bit differently, WotC never bothers publishing details, and figuring that out takes forever. Basically until http://www.lethe.xyz/mtg/collation/index.html figures out details, I'm unlikely to guess them correctly, so for now I just implement no-showcase boosters. This is something I'd like to have a more systematic way to deal with. (https://github.com/mtgjson/mtgjson/issues/784 talks about showcase cards)

**Comment by fverdoja** [comment]
Thanks for the clarification.
It seems you are correct, cards 20/151 are in the card list, but their uuids are different than the ones in the booster data. In the card list, they are:
```
 20	edc7c20c-3cb1-557f-b79a-6b391e02c67b
151	ba2a5b47-8058-5de2-bc8b-28b57b56615e
```
So I guess this will solve itself next build?

**Comment by taw** [comment]
Yeah, I can confirm cards 20, 151, and 285 changed uuids this week. Updated data should be automatically picked up for next week's update.

**Comment by ZeldaZach** [comment]
This issue appears to be resolved, with a change on Taw's side :)
