### ISSUE TITLE
Clash Pack

### ISSUE THREAD

**Issue by jenjia** [mtgjson/mtgjson#83]
There are currently 18 Clash Pack promos, but MTGJson just has 12.

**Comment by Sembiance** [comment]
Promo card data comes from magiccards.info and they haven't updated their site yet with the new data.

**Comment by cbeiraod** [comment]
The card numbers for the 12 cards in MTGJson do not seem to make sense.

magiccards.info numbers these cards from 1 to 12, on mtgjson the numbers 1, 3, 4, 5, 6 are repeated, with there being a card numbered 2 and a card numbered 8.

Since the card number can be used to distinguish cards within a set, I believe it would make most sense to either follow magiccards.info (1 to 12 or up to 18 once the newer promos are recognised as well) or to separate the clash pack promos and number from 1 to 6, as wizards seems to do as seen on the cards (see the naming CP1 and CP2):
![Hydra Broodmaster](http://magiccards.info/scans/en/clash/4.jpg) ![Courser of Kruphix](http://magiccards.info/scans/en/clash/12.jpg)

I would be happy to help implement these changes, but I am just a downstream user of the json files provided by mtgjson and do not know much about the internals on how the json files are generated. (Sorry for adding onto this issue #83 but I was not sure if it was worthwhile opening a new issue for this since it is so closely related)
