### ISSUE TITLE
Scryfall IDs not matching? 

### ISSUE THREAD

**Issue by karlosss** [mtgjson/mtgjson#863]
Hi!

Maybe I just don't know how to use it. I would like to fetch card images from somewhere, however I struggle with that. I start with [ModernAtomic.json](https://mtgjson.com/api/v5/ModernAtomic.json), which has a `scryfallOracleId` in the `identifiers` field of each card. However, when I use this ID in `https://c1.scryfall.com/file/scryfall-cards/large/front/6/9/${id}?1619398799`, the image is not found. The same is true when I follow the link format in [mtgjson FAQ](https://mtgjson.com/faq/#how-do-i-access-a-card-s-imagery). Multiverse ID is unfortunately not present in the file, so I cannot make use of Gatherer. How do I thus get the images?

Thank you!

**Comment by ZeldaZach** [comment]
Hi there @karlosss while this isn't a MTGJSON issue per say, I'm more than happy to point you in the right direction.

Per Scryfall Documentation: OracleIDs are a bit different than main IDs, since every printing of a specific card will have the same OracleID. The way you tried to load images from the CDN is explicitly denounced by the Scryfall Team, since they shard images for efficiency.

You can get _all_ printings of the card via `https://api.scryfall.com/cards/oracle/${scryfallOracleId}` which you can then iterate for images. For simplicity, you can simply do something like

```python3
import requests

response_object = requests.get("https://api.scryfall.com/cards/oracle/${scryfallOracleId}").json()
if response_object == "list" and response_object.get("data"):
    return response_object["data"][0]["image_uris"]["normal"]
```

Hopefully this helps you out! If you have any other issues or questions about the project, feel free to hit us up on [Discord](https://mtgjson.com/discord) or a new ticket :)
