### ISSUE TITLE
source text issue

### ISSUE THREAD

**Issue by liquera** [mtgjson/mtgjson#874]
### Steps to reproduce
Open cards.csv or .json anyway you want.
Do a simple search for "lifelinkat", for instance.

### What is expected?
There should be a space between keyword habilities and card's specific habilities.

### What is actually happening?
Specific habilities are being appended without space, generating unwanted text data.
i.e.: FlyingWhen, FlyingLandfall, lifelinkAt, creatureWhen, VigilanceSacrifice

### Other relevant information
That's an issue in the WotC source files. They do have a separated column for the keyword habilities in the English cards file, allowing me to fix the issue on my side. But that's not true for foreign data, though, and there's no space between keyword habilites and specific habilities there. Why does it matter? It creates false word data for whoever wants to use MTG database for corpus linguistics or anything similar to that.

**Comment by ZeldaZach** [comment]
Hi there @liquera ! Sorry I missed your ticket originally. I took a look just now at AllPrintings.json and cards.csv, and I see what went wrong. When pulling data in from Gatherer, because they use separate divs for each line, I was inadvertently dropping the implicit line break. Will see what I can do soon :)
