### ISSUE TITLE
foreignData field empty for double cards

### ISSUE THREAD

**Issue by couitchy** [mtgjson/mtgjson#884]
#### Version(s) tested against
5.1.0+20211208
#### Description of Bug
I noticed the foreignData field is empty for double cards.
For example, Baithook Angler // Hook-Haunt Drifter (Innistrad: Midnight Hunt) have no foreign data at all.
The field is correct for other non double cards though.

**Comment by ZeldaZach** [comment]
Hey @couitchy! I'm pretty sure this is a dupe, but I can't find the original. In any case, the reason foreignData is missing for Baithook Angler (and most other double-sided cards) is because Gatherer doesn't offer translations on these cards. Most of these translation pages only have the English version of the text, making translation a nightmare as we don't have any image recognition to pull the data right off the cards at this time. 

If/when Gatherer better supports these cards, or I find someone to help translate cards for the project, we won't be able to fix this issue. Sorry for the letdown :(
