### ISSUE TITLE
Many commonly reprinted cards: wrong artist in several sets

### ISSUE THREAD

**Issue by flyingmutant** [mtgjson/mtgjson#90]
Both [ME3](http://magiccards.info/me3/en/121.html) and [ME2](http://magiccards.info/me2/en/167.html) should have «Sandra Everingham», like [ME4](http://magiccards.info/me4/en/156.html) does.

**Comment by flyingmutant** [comment]
As I go looking though the data, almost all cards that were reprinted many times have issues with artist names.

Would you accept a PR fixing them all at once?

**Comment by lsmoura** [comment]
There are many cards with wrong artists. I don't know how WoTC could made so many mistakes...

Yes, you can submit a push request fixing the code. I'd be happy to commit it! It should mostly be handled on C.js.

**Comment by gwax** [comment]
PRs can be submitted in shared/set_configs/... to introduce corrections.

I would be happy to rebuild things with any corrections that people submit.

Since this has been open without movement for a very long time, I am going to close it as a "won't fix" bug. Folks are welcome to reopen but please provide a list of corrections or a PR.
