### ISSUE TITLE
AFR Dungeon Cards Have manaValue null

### ISSUE THREAD

**Issue by aaronmallen** [mtgjson/mtgjson#901]
#### Version(s) tested against

5.2.0+20211228

#### Description of Bug
Three cards having type "Dungeon" have `manaValue` `null` instead of `0`

**Comment by ZeldaZach** [comment]
Dungeons are not castable cards, so they implicitly don't have a mana cost / mana value. They're akin to a token. 

Any reason you feel Dungeons should have a mana value established?

**Comment by aaronmallen** [comment]
The dungeon cards are the only cards with manaValue `null` (as of when this issue was created) even basic lands have manaValue `0`. Is there any reason these cards should not follow that pattern?

**Comment by ZeldaZach** [comment]
Basic lands can be played in a deck and played. It makes sense they have no mana value established. Dungeons, however, are kind of like tokens (think Clue, Treasure, etc) in regards to having no mana cost since you can't play them in a deck, but Dungeons can only exist in the Command Zone (similar to Emblems).

**Comment by aaronmallen** [comment]
https://discord.com/channels/224178957103136779/448295284137656342/925904885289975901
