### ISSUE TITLE
Changes to AllPrices

### ISSUE THREAD

**Issue by pnametala** [mtgjson/mtgjson#927]
AllPrices.json is roughly 800MB now and is quite a problem to download/iterate over it on a daily base.

A few suggestions that might improve the usability.

Publish AllPrices as both JSON and CSV.

Publish a new file (LatestPrices) with the latest available price for each card.

Thanks in advance :)

**Comment by van-riper** [comment]
It shouldn't be a problem to download it, since that file also is available compressed in zip, bz2, gz, and xz, all of which are under 80MB. I'm not sure how a csv version could work for this model. The only reasonable way I can think to implement that is to have a row for each card, and a column for each day. That would require an unnecessarily large file size to work. This is disregarding that there are multiple card vendors that each have their own prices, in paper and online.

If you can think of a better way to model the data, let us know, but at the moment this seems like it wouldn't work

**Comment by ZeldaZach** [comment]
This feels like a dupe to #673
