### ISSUE TITLE
Incorrect data on some cards

### ISSUE THREAD

**Issue by notverymoe** [mtgjson/mtgjson#937]
#### Version(s) tested against
MTGJSON 5.2.0+20220418, AtomicCards.json from website downloads.

#### Description of Bug

Some incorrect card data:
- Trial and Error (Test Card)
- Old Fogey (Unhinged)
- Xyru Specter (Test Card)
- Throat Wolf (Test Card)
- Spellbinding Soprano (Regular Card)

I don't know for certain, but I believe they have the following issues:
- Have the had their Summon card type errata'd, except for Old Fogey (of course)
- Gatherer seems to indicate that the type after "Summon" is a subtype, if I'm reading it right, but mtgjson lists them as card types (Trial and Error is explicitly an "Elemental Instant" however)
- Spellbinding Soprano doesn't have the above issues, but is reported as a "Crature"

**Comment by zqft9001** [comment]
This looks to be mostly (but not entirely) a Gatherer issue, and technically anything it says on Gatherer is as "correct" as it gets.

Gatherer still has the type "Summon" for Xyru Specter, Throat Wolf, and Old Fogey, so that appears to be accurate.:
https://gatherer.wizards.com/Pages/Search/Default.aspx?action=advanced&type=+[%22Summon%22]

For the subtype issue, Gatherer reports "Wolf" as a card type for Throat Wolf, subtypes would be after the —. Xyru Specter, however, is incorrect as it's "Summon — Specter." Looks like it's also incorrect on Scryfall, I submitted a bug report to them so they should fix that and it'll flow down.

Old Fogey:
https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=479456
Summon — Dinosaur

Throat Wolf:
https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=476195
Summon Wolf

Xyru Specter (incorrect per gatherer, submitted report to scryfall):
https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=476181
Summon — Specter
https://scryfall.com/card/cmb2/51/xyru-specter
Summon Specter

Trial and Error appears to be correct:
https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=476198
Elemental Instant — Fire

Spellbinding Soprano appears to now be correctly reporting as a Creature. Probably some kind of typo somewhere as it's a preview card currently.

As of 5.2.0+20220426
| NAME | TYPE | types | subtypes | UUID | scryfallid | 
| --- | --- | --- | --- | --- | --- | 
| Old Fogey | Summon — Dinosaur | Summon | Dinosaur | 17ccd14d-a756-5f95-a80d-6b423ae525b9 | ccae52dd-3ffd-4974-8915-61f816d29a64 | 
| Old Fogey | Summon — Dinosaur | Summon | Dinosaur | 9d36443d-3ee5-598d-9b12-8cce6eafe6cf | e6ce51c4-16ea-48e8-a976-402b15450b88 | 
| Old Fogey | Summon — Dinosaur | Summon | Dinosaur | 17ad0580-e193-5bf1-9df1-1db70c3532c4 | ac29717c-c586-4adb-94a3-f41096cce110 | 
| Spellbinding Soprano | Creature — Human Bard | Creature | Human,Bard | 91432b4d-7d2c-5944-9514-494ebd385e07 | 248d71f9-89ef-492e-a854-a890f7d91ef8 | 
| Spellbinding Soprano | Creature — Human Bard | Creature | Human,Bard | 216d216e-1703-54bd-af6b-ced47a85c17b | ba347203-3792-41a3-8888-424ead494f21 | 
| Throat Wolf | Summon Wolf | Summon,Wolf | \N | c8e709b1-5679-57c6-b0bd-cc578af132c6 | d06910b3-2458-4c13-a7d3-8972522a44f7 | 
| Throat Wolf | Summon Wolf | Summon,Wolf | \N | d3b1ebc5-f51b-56cb-beb6-62eb08e7e584 | 144280de-1493-41e5-a537-83339c1ae26e | 
| Trial and Error | Elemental Instant — Fire | Elemental,Instant | Fire | 1edf860e-69aa-52f8-a792-3c8041b756af | 3b0059aa-a224-484b-8275-4fa57bcbc91b | 
| Trial and Error | Elemental Instant — Fire | Elemental,Instant | Fire | f6508a43-1c2c-59e9-b213-6fec99af1c7f | 5ea53e12-bc2c-461d-b49c-79205a4beb27 | 
| Xyru Specter | Summon Specter | Summon,Specter | \N | f608f779-bba6-5924-b6e8-32f3e2627330 | 2056f09e-2874-4ae7-95d2-8c53513a0648 | 
| Xyru Specter | Summon Specter | Summon,Specter | \N | 59c2f908-242b-57a9-912d-78c0f6f0ca0b | 35db376d-187c-4f88-a784-4cfde5292499 |

**Comment by notverymoe** [comment]
Oh, sorry for the misunderstanding on my part for a few of those! Seems really weird they have errata rulings on Xyru and Throat but haven't applied them. Maybe I can lodge something with wizards on that...  I'll try a poke, you never know right?

Thanks for reporting upstream, I'll make sure to do in the future

**Comment by zqft9001** [comment]
Yeah, they're very lax about updating "funny" cards on Gatherer. Looks like Scryfall has already updated Xyru Specter, so that should be correct in the next build.

**Comment by notverymoe** [comment]
They got back to me, they've apparently forwarded to an internal department. So we'll see if they agree and get around to it, or not

**Comment by ZeldaZach** [comment]
Thanks for taking the lead on this @zqft9001 ! I'm taking a look at the history and it seems like things are working as they should. Rulings on Trial and Error (Surprised they exist...) "Elemental is a card type, and Fire is an elemental type. This has no relation to the creature type Elemental. If an effect refers to an Elemental, it refers to the creature type."

For the other cards, things look good now, so thanks for handling those reports. If there's further issues, please let me know!
