### ISSUE TITLE
"New Capenna Golden Age Promo" Rafiq of the Many ALA:250 is not actually from ALA

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#959]
mtgjson recently added this "New Capenna Golden Age Promo" card to ALA set: https://scryfall.com/card/ala/250/rafiq-of-the-many

It should not be in ALA set, it wasn't anywhere close to ALA, it's just a promo card printed well more than a decade later.

It should be moved to PNCC or PLIST or something (even PALA would be weird).

Gatherer also doesn't have it (in ALA or otherwise), as it doesn't usually do such promos.

**Comment by kodawah** [comment]
the card was sadly marked as ALA by wotc, I agree with the sentiment, but categorizing it differently would create even more confusion

**Comment by taw** [comment]
And every card in PDMU is tagged DMU on the card, every card in OVOC is tagged VOC on the card etc. It never stopped mtgjson before.

**Comment by ZeldaZach** [comment]
Did some digging through this, and I'm unfortunately inclined to leave it as-is. The card was printed with the exact same set symbol, code, and incremental collector number. While it's a bit unorthodox for a company to add new cards to a set from the past, it technically fits the requirements to be there. Especially since it doesn't have the LIST planeswalker symbol, it just doesn't feel right to put it into PLIST or PNCC in my opinion. The set is still classified as 249 cards, with a total set size of 250. The new card also has a unique date attached, which devs should know from our docs that the card came later (Similar to FNM style sets).

I hope they don't do this again. #Meld

**Comment by taw** [comment]
> I hope they don't do this again. #Meld

So now that it's clear that they're doing it again, and likely plan to keep doing it going forward, can we move all such cards from XXX sets to pXXX?

It looks like the whole Pretor cycle got this treatment, so we might need to revisit it.

**Comment by kodawah** [comment]
@taw while annoying to deal with for sealed/booster purposes, I don't think deviating from upstream is a good idea

could we think of an alternative solution, for example validating a set with the release date (cards have OriginalReleaseDate field available for that) or alternatively like a list of ids to skip or consider depending on the set?

**Comment by taw** [comment]
These are promo cards. We already have pXXX sets, and nobody is surprised that cards can get added to them. I really don't see why not just add it there.

I'm mostly annoyed by this specific issue as it complicated my booster logic; I can do some workarounds for that on my end, but it feels like the problem is self-made. And as for upstream, none of such cards are even on Gatherer. No idea why scryfall decided to stuff them into base sets.

**Comment by kodawah** [comment]
> These are promo cards.

I think the definition of promo is inconsistent, at least on wotc side. These are cards that are found in boosters coming from a standard set, so they are not promo, but rather part of the "boosterfun" initiative.

> No idea why scryfall decided to stuff them into base sets.

Because they try to follow the set code / numbering printed on the card when possible

For the record I'm also not a fan of this style of releases, wotc should have made a separate set code like for the dragons endgame or something.
