### ISSUE TITLE
Reversible cards don't have Scryfall Oracle ID

### ISSUE THREAD

**Issue by jivanpal** [mtgjson/mtgjson#973]
#### Version(s) tested against

Version 5.2.0+20221108

#### Description of Bug

"Reversible cards" (currently only those from the Secret Lair Drop "Heads I Win, Tails You Lose") such as "Okaun, Eye of Chaos // Okaun, Eye of Chaos" don't have an identifier `scryfallOracleId`, despite arguably the sensible value for this being that of the corresponding regular card which the reversible card has the same Oracle text as on both its faces, i.e. `7dec219b-96d1-4d4c-b3ac-15eda9d2ccc6` for Okaun. Indeed, Scryfall displays these reversible cards alongside their regular counterparts.

Additionally, MTGJSON treats these cards as being separate Oracle entries, being given their own JSON key in the Card (Atomic) data, and their own `name`, that is formatted as for any other double faced card, e.g. "Okaun, Eye of Chaos // Okaun, Eye of Chaos" rather than just "Okaun, Eye of Chaos". Is this really the desired behaviour? Would it not be better to put the reversible cards alongside the corresponding regular cards in the Card (Atomic) data, and use the corresponding `scryfallOracleId` for them?

**Comment by ZeldaZach** [comment]
I gotta think about this one some more. Any opinions on this @kodabb

**Comment by kodawah** [comment]
> Additionally, MTGJSON treats these cards as being separate Oracle entries, being given their own JSON key in the Card (Atomic) data, and their own name, that is formatted as for any other double faced card, e.g. "Okaun, Eye of Chaos // Okaun, Eye of Chaos" rather than just "Okaun, Eye of Chaos". Is this really the desired behaviour? 

I think that's the intended behavior because it's a double faced card so it makes sense that that property is reflect in the name - i can totally see a future in which there is a SLD Propaganda which is not DFC, so you kinda need a way to tell them apart

as for the `scryfallOracleId` im not sure because i don't use that field, but i think probably it should behave like the other identifiers, like for scryfallId

**Comment by jivanpal** [comment]
> i can totally see a future in which there is a SLD Propaganda which is not DFC, so you kinda need a way to tell them apart

You would be able to tell them apart by their collector number or the presence of the `face` property. Since they would have the same English card name, their Oracle text would be the same, which is the point of contention here: why is the card name different, and why does the card object lack an Oracle ID?

I haven't yet looked at whether/how MTGJSON handles double-faced token cards, but assuming it does, and it uses different Oracle IDs for the front face and the back face, then for consistency perhaps it is worth handling reversible cards in the same way, except that the Oracle IDs of the front face and back face would be the same in this case.

**Comment by kodawah** [comment]
> You would be able to tell them apart by their collector number or the presence of the face property. 

I mean, every card is discernible by looking at other fields. I personally like the fact that you can tell DFC just by the name.

**Comment by ZeldaZach** [comment]
I've gone ahead and put a fix up for the missing Scryfall Oracle Ids (Which is the main goal of this ticket), however I'm currently inclined to leave these as separate entries in the Atomics for the moment. If you disagree/want to cut a new ticket to discuss that bit in greater detail, I'd be happy to continue the discussion there!

**Comment by jivanpal** [comment]
@kodabb You cannot. Consider e.g. split cards, such as [Alive // Well](https://scryfall.com/card/dgm/121/alive-well).

**Comment by kodawah** [comment]
> @kodabb You cannot. Consider e.g. split cards, such as [Alive // Well](https://scryfall.com/card/dgm/121/alive-well).

@jivanpal I'm not sure how this point is related: split cards have a different `layout` field, as well as two different sides (`a`, and `b`) at least in AllPrintings file. I would not usse the atomic file for anything personally

**Comment by jivanpal** [comment]
@kodabb All I mean to say is that the presence of "//" in the card name doesn't tell you anything other than that it has two parts. Whether it is a DFC, Adventure, Aftermath etc. should be determined from `layout`, as you mention.

**Comment by kodawah** [comment]
@jivanpal yeah exactly - if there is " // " in the name you should check `layout`, instead of having to check `layout` or `side` for every single card. Additionally there is no crossover between layout types within a single set, like ZNR only had DFC but no split cards, same for INV with split card but no other weird layouts. My point is that every card is discernible by looking at other fields.

Do you think this property should be better documented or exported with a boolean field? How would you represent corner cases such as [this unhinged card](https://scryfall.com/card/und/75/who-what-when-where-why)? I would recommend writing a proposal and filing a new bug, I'm sure it can be accommodated in some capacity.
